apiVersion: v1
kind: ConfigMap
metadata:
  name: gpu-sharing-config
  namespace: platform-kernel
data:
  time-slicing-config.yaml: |
    version: v1
    sharing:
      timeSlicing:
        resources:
        - name: nvidia.com/gpu
          replicas: 4
