{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "gentian-app.fullname" . }}
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
    - host: {{ .Values.ingress.subDomain }}.PLACEHOLDER_TENANT_DOMAIN
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: {{ include "gentian-app.fullname" . }}-api
                port:
                  number: 8000
          - path: /healthz
            pathType: Exact
            backend:
              service:
                name: {{ include "gentian-app.fullname" . }}-api
                port:
                  number: 8000
          - path: /readyz
            pathType: Exact
            backend:
              service:
                name: {{ include "gentian-app.fullname" . }}-api
                port:
                  number: 8000
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "gentian-app.fullname" . }}-web
                port:
                  number: 80
{{- end }}
