apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - service-aliases.yaml
  - release.yaml

configMapGenerator:
  - name: nubus-base-values
    namespace: gentian-dev
    files:
      - values.yaml=values/_base.yaml
  - name: nubus-dev-values
    namespace: gentian-dev
    files:
      - values.yaml=values/dev.yaml
  - name: nubus-dev-udm-listener-nats-patch
    namespace: gentian-dev
    files:
      - mq_adapter_nats.py=patches/mq_adapter_nats.py
  - name: nubus-dev-ldap-gentian-acl
    namespace: gentian-dev
    files:
      - 92-gentian-tenant-acl.sh=patches/92-gentian-tenant-acl.sh

generatorOptions:
  disableNameSuffixHash: true
