#!/usr/bin/env python3
# SPDX-License-Identifier: AGPL-3.0-only
# SPDX-FileCopyrightText: 2025 Gentian GmbH
#
# Patch slapd.conf to allow members of cn=Tenant Admins,cn=groups,<ldap_base>
# write access to cn=temporary,cn=univention,<ldap_base>.
#
# This script runs as /entrypoint.d/92-gentian-tenant-acl.sh before slapd is
# launched. It inserts a 'by set=...' clause for cn=Tenant Admins before the
# existing 'by set=...' clause for cn=Domain Admins in the three cn=temporary
# ACL blocks generated by UCR template 70univention-ldap-server_acl-master-end.
#
# Background: when a tenant admin (member of cn=admins_<tenant>,ou=<tenant>)
# creates a new user via UDM REST API, UDM writes a UID lock object to
# cn=<uid>,cn=uid,cn=temporary,cn=univention. Without this ACL entry the
# operation fails with "Permission denied: Can not modify lock time".
#
# The fix uses a shared group cn=Tenant Admins,cn=groups,<ldap_base> which
# the gentian-os controller (ldap_reconciler.go) populates with each tenant
# admin group (cn=admins_<tenant>) as a nested group. With ldap/acl/nestedgroups
# enabled, uniqueMember* traversal makes all tenant admins satisfy the ACL.
#
# Idempotent: exits 0 without changes if the patch is already applied.
import re
import sys

SLAPD_CONF = "/etc/ldap/slapd.conf"
UCR_BASE_CONF = "/etc/univention/base.conf"

# Read ldap/base from UCR configuration
ldap_base = None
try:
    with open(UCR_BASE_CONF) as f:
        for line in f:
            if line.startswith("ldap/base:"):
                ldap_base = line.split(":", 1)[1].strip()
                break
except FileNotFoundError:
    print(f"ERROR: {UCR_BASE_CONF} not found", file=sys.stderr)
    sys.exit(1)

if not ldap_base:
    print("ERROR: ldap/base not found in UCR config", file=sys.stderr)
    sys.exit(1)

tenant_admins_group = f"cn=Tenant Admins,cn=groups,{ldap_base}"
tenant_admins_by = f'   by set="user & [{tenant_admins_group}]/uniqueMember*" write\n'
domain_admins_by = f'   by set="user & [cn=Domain Admins,cn=groups,{ldap_base}]/uniqueMember*" write\n'

with open(SLAPD_CONF) as f:
    content = f.read()

# Idempotency check
if "Tenant Admins" in content:
    print("slapd.conf already patched for Tenant Admins, skipping.")
    sys.exit(0)

# Split into 'access to' blocks; only patch blocks targeting cn=temporary.
# This avoids touching unrelated Domain Admins ACL entries (samba, computers, etc.).
blocks = re.split(r"(?=^access to )", content, flags=re.MULTILINE)
patched_count = 0
new_blocks = []
for block in blocks:
    if "cn=temporary" in block and domain_admins_by in block:
        block = block.replace(domain_admins_by, tenant_admins_by + domain_admins_by, 1)
        patched_count += 1
    new_blocks.append(block)

if patched_count == 0:
    print(
        "WARNING: No cn=temporary blocks with Domain Admins pattern found in slapd.conf",
        file=sys.stderr,
    )
    sys.exit(1)

with open(SLAPD_CONF, "w") as f:
    f.write("".join(new_blocks))

print(
    f"Patched slapd.conf: added {tenant_admins_group} "
    f"to {patched_count} cn=temporary ACL block(s)."
)
