apiVersion: v1
kind: Service
metadata:
  name: {{ include "gentian-os.fullname" . }}-lifecycle
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "gentian-os.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "gentian-os.selectorLabels" . | nindent 4 }}
  ports:
    - name: lifecycle
      port: {{ .Values.appLifecycle.port }}
      targetPort: lifecycle
      protocol: TCP
