{{- if and .Values.cloudflare.apiTokenSecretRef.name .Values.cloudflare.apiTokenSecretRef.openbaoPath }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.cloudflare.apiTokenSecretRef.name }}
  labels:
    {{- include "gentian-os.labels" . | nindent 4 }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao
  target:
    name: {{ .Values.cloudflare.apiTokenSecretRef.name }}
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: {{ .Values.cloudflare.apiTokenSecretRef.key | default "api-token" | quote }}
      remoteRef:
        key: {{ .Values.cloudflare.apiTokenSecretRef.openbaoPath | quote }}
        property: {{ .Values.cloudflare.apiTokenSecretRef.key | default "api-token" | quote }}
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: "zone-id"
      remoteRef:
        key: {{ .Values.cloudflare.apiTokenSecretRef.openbaoPath | quote }}
        property: "zone-id"
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: "tunnel-cname"
      remoteRef:
        key: {{ .Values.cloudflare.apiTokenSecretRef.openbaoPath | quote }}
        property: "tunnel-cname"
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
{{- end }}
