{{- if .Values.sharedAppsNamespace.create }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.sharedAppsNamespace.name }}
  labels:
    {{- include "gentian-os.labels" . | nindent 4 }}
{{- end }}
