apiVersion: v1
kind: Service
metadata:
  name: {{ include "gentian-os.fullname" . }}-metrics
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "gentian-os.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "gentian-os.selectorLabels" . | nindent 4 }}
  ports:
    - name: metrics
      port: 8080
      targetPort: metrics
      protocol: TCP
