apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: minio-credentials
  namespace: gentian-infra-dev
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: openbao
    kind: ClusterSecretStore
  target:
    name: minio-credentials
    creationPolicy: Owner
  data:
    - secretKey: root-user
      remoteRef:
        key: gentian-os/kernel/storage/minio
        property: root_user
    - secretKey: root-password
      remoteRef:
        key: gentian-os/kernel/storage/minio
        property: root_password
    - secretKey: ums-password
      remoteRef:
        key: gentian-os/kernel/storage/minio
        property: ums_password
    - secretKey: nextcloud-password
      remoteRef:
        key: gentian-os/kernel/storage/minio
        property: nextcloud_password
    - secretKey: openxchange-password
      remoteRef:
        key: gentian-os/kernel/storage/minio
        property: openxchange_password
    - secretKey: openproject-password
      remoteRef:
        key: gentian-os/kernel/storage/minio
        property: openproject_password
    - secretKey: notes-password
      remoteRef:
        key: gentian-os/kernel/storage/minio
        property: notes_password
    - secretKey: migrations-password
      remoteRef:
        key: gentian-os/kernel/storage/minio
        property: migrations_password
    - secretKey: dovecot-password
      remoteRef:
        key: gentian-os/kernel/storage/minio
        property: dovecot_password
