apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: minio-provisioning-users
  namespace: gentian-infra-dev
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: openbao
    kind: ClusterSecretStore
  target:
    name: minio-provisioning-users
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        migration_user: |
          username=migration_user
          password={{ .migrations_password }}
          disabled=false
          policies=migrations-bucket-policy
          setPolicies=true
        nextcloud_user: |
          username=nextcloud_user
          password={{ .nextcloud_minio_password }}
          disabled=false
          policies=nextcloud-bucket-policy
          setPolicies=true
        ums_user: |
          username=ums_user
          password={{ .ums_password }}
          disabled=false
          policies=ums-bucket-policy
          setPolicies=true
  data:
    - secretKey: migrations_password
      remoteRef:
        key: gentian-os/kernel/storage/minio
        property: migrations_password
    - secretKey: nextcloud_minio_password
      remoteRef:
        key: gentian-os/kernel/apps/nextcloud
        property: minio_password
    - secretKey: ums_password
      remoteRef:
        key: gentian-os/kernel/storage/minio
        property: ums_password
