# =============================================================================
# Policies
# =============================================================================
# ESO gets read access to all kernel secrets and all tenant app secrets.
# Tenant isolation is enforced by Kubernetes RBAC on the resulting K8s Secrets;
# ESO itself needs a single cluster-wide read role.
#
# Per-tenant direct-access policies (for tenant pod → OpenBao reads without ESO)
# are generated by the openbao-tenant-policy module, instantiated once per tenant.

resource "vault_policy" "eso_read" {
  name = "eso-read"
  policy = <<-EOT
    # Read-only access to all kernel credentials
    path "secret/data/gentian-os/kernel/*" {
      capabilities = ["read"]
    }
    path "secret/metadata/gentian-os/kernel/*" {
      capabilities = ["list"]
    }

    # Read-only access to all tenant app credentials (ESO distributes to namespaces)
    path "secret/data/gentian-os/tenants/*/apps/*/*" {
      capabilities = ["read"]
    }
    path "secret/metadata/gentian-os/tenants/*" {
      capabilities = ["list"]
    }
  EOT
}

# Tofu runner needs read+write access to seed and read secrets used by helm
# releases managed by the infra-workspaces Terraform workspace.
resource "vault_policy" "tofu_write" {
  name = "tofu-write"
  policy = <<-EOT
    # Read/write access for Tofu runner to manage all gentian-os secrets
    path "secret/data/gentian-os/*" {
      capabilities = ["create", "read", "update", "delete"]
    }

    path "secret/metadata/gentian-os/*" {
      capabilities = ["list", "read", "delete"]
    }

    # The vault provider creates a limited child token for each operation.
    # This requires auth/token/create capability on the token itself.
    path "auth/token/create" {
      capabilities = ["update"]
    }

    # Allow the runner to look up its own token (required by vault provider v4).
    path "auth/token/lookup-self" {
      capabilities = ["read"]
    }
  EOT
}
