package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// IntegrationBindingSpec defines the desired state of an IntegrationBinding.
type IntegrationBindingSpec struct {
	// Contract is the name of the integration contract being fulfilled
	// (e.g., "file-store", "filepicker", "central-navigation").
	// +kubebuilder:validation:Required
	// +kubebuilder:validation:MinLength=1
	// +kubebuilder:validation:Pattern=`^[a-z0-9-]+$`
	Contract string `json:"contract"`

	// Provider identifies the app that fulfils the contract.
	// +kubebuilder:validation:Required
	Provider AppEndpoint `json:"provider"`

	// Consumer identifies the app that consumes the contract.
	// +kubebuilder:validation:Required
	Consumer AppEndpoint `json:"consumer"`

	// Capabilities lists the specific contract capabilities being granted.
	// +optional
	Capabilities []string `json:"capabilities,omitempty"`

	// Auth configures how the consumer authenticates to the provider.
	// +optional
	Auth *BindingAuth `json:"auth,omitempty"`
}

// AppEndpoint references an app instance within a namespace.
type AppEndpoint struct {
	// App is the name of the app (corresponds to the AppProfile name).
	// +kubebuilder:validation:Required
	// +kubebuilder:validation:MinLength=1
	App string `json:"app"`

	// Namespace is the Kubernetes namespace where the app is running.
	// +kubebuilder:validation:Required
	// +kubebuilder:validation:MinLength=1
	Namespace string `json:"namespace"`
}

// BindingAuth describes the authentication method used by this binding.
type BindingAuth struct {
	// Method is the authentication protocol.
	// +kubebuilder:validation:Required
	// +kubebuilder:validation:Enum=oidc-token-exchange;service-account;api-key
	Method string `json:"method"`

	// VaultPath is the OpenBao path where shared credentials are stored.
	// Typically: gentian-os/tenants/{tenant}/contracts/{contract}
	// +optional
	VaultPath string `json:"vaultPath,omitempty"`
}

// IntegrationBindingStatus holds the observed state of an IntegrationBinding.
type IntegrationBindingStatus struct {
	// State summarises whether the binding is functional.
	// +optional
	State IntegrationBindingState `json:"state,omitempty"`

	// Conditions provides detailed status conditions.
	// +optional
	// +listType=map
	// +listMapKey=type
	Conditions []metav1.Condition `json:"conditions,omitempty"`

	// SecretRef points to the Kubernetes Secret containing the shared credentials
	// synced by ESO from the VaultPath.
	// +optional
	SecretRef *LocalSecretRef `json:"secretRef,omitempty"`

	// LastRotation is when the binding credentials were last rotated.
	// +optional
	LastRotation *metav1.Time `json:"lastRotation,omitempty"`

	// ObservedGeneration is the last processed spec generation.
	// +optional
	ObservedGeneration int64 `json:"observedGeneration,omitempty"`
}

// LocalSecretRef is a reference to a Secret in the same namespace.
type LocalSecretRef struct {
	// Name is the Secret name.
	// +kubebuilder:validation:Required
	Name string `json:"name"`
}

// IntegrationBinding is the Schema for the integrationbindings API.
//
// IntegrationBinding is namespace-scoped — it lives in the tenant's namespace
// and is auto-generated by the orchestrator when both the provider and consumer
// apps are present in a tenant's app list and the AppProfile declares compatible
// integration contracts. The binding provisions shared credentials in OpenBao
// and wires the authentication method between provider and consumer.
//
// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Namespaced,shortName=ib;ibs
// +kubebuilder:printcolumn:name="Contract",type=string,JSONPath=`.spec.contract`
// +kubebuilder:printcolumn:name="Provider",type=string,JSONPath=`.spec.provider.app`
// +kubebuilder:printcolumn:name="Consumer",type=string,JSONPath=`.spec.consumer.app`
// +kubebuilder:printcolumn:name="State",type=string,JSONPath=`.status.state`
// +kubebuilder:printcolumn:name="Age",type=date,JSONPath=`.metadata.creationTimestamp`
type IntegrationBinding struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   IntegrationBindingSpec   `json:"spec,omitempty"`
	Status IntegrationBindingStatus `json:"status,omitempty"`
}

// IntegrationBindingList contains a list of IntegrationBinding.
// +kubebuilder:object:root=true
type IntegrationBindingList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []IntegrationBinding `json:"items"`
}

func init() {
	SchemeBuilder.Register(&IntegrationBinding{}, &IntegrationBindingList{})
}
