//go:build !ignore_autogenerated

/*
Copyright 2026 Gentian Organization.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	networkingv1 "k8s.io/api/networking/v1"
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *APIIntegration) DeepCopyInto(out *APIIntegration) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new APIIntegration.
func (in *APIIntegration) DeepCopy() *APIIntegration {
	if in == nil {
		return nil
	}
	out := new(APIIntegration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AllowConsumerSpec) DeepCopyInto(out *AllowConsumerSpec) {
	*out = *in
	if in.Scope != nil {
		in, out := &in.Scope, &out.Scope
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AllowConsumerSpec.
func (in *AllowConsumerSpec) DeepCopy() *AllowConsumerSpec {
	if in == nil {
		return nil
	}
	out := new(AllowConsumerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AllowedMacWaiver) DeepCopyInto(out *AllowedMacWaiver) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AllowedMacWaiver.
func (in *AllowedMacWaiver) DeepCopy() *AllowedMacWaiver {
	if in == nil {
		return nil
	}
	out := new(AllowedMacWaiver)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AppCatalogue) DeepCopyInto(out *AppCatalogue) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AppCatalogue.
func (in *AppCatalogue) DeepCopy() *AppCatalogue {
	if in == nil {
		return nil
	}
	out := new(AppCatalogue)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AppCatalogue) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AppCatalogueList) DeepCopyInto(out *AppCatalogueList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AppCatalogue, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AppCatalogueList.
func (in *AppCatalogueList) DeepCopy() *AppCatalogueList {
	if in == nil {
		return nil
	}
	out := new(AppCatalogueList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AppCatalogueList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AppCatalogueSpec) DeepCopyInto(out *AppCatalogueSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AppCatalogueSpec.
func (in *AppCatalogueSpec) DeepCopy() *AppCatalogueSpec {
	if in == nil {
		return nil
	}
	out := new(AppCatalogueSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AppCatalogueStatus) DeepCopyInto(out *AppCatalogueStatus) {
	*out = *in
	if in.Apps != nil {
		in, out := &in.Apps, &out.Apps
		*out = make([]CatalogueEntry, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.LastUpdated != nil {
		in, out := &in.LastUpdated, &out.LastUpdated
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AppCatalogueStatus.
func (in *AppCatalogueStatus) DeepCopy() *AppCatalogueStatus {
	if in == nil {
		return nil
	}
	out := new(AppCatalogueStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AppEndpoint) DeepCopyInto(out *AppEndpoint) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AppEndpoint.
func (in *AppEndpoint) DeepCopy() *AppEndpoint {
	if in == nil {
		return nil
	}
	out := new(AppEndpoint)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AppGrant) DeepCopyInto(out *AppGrant) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AppGrant.
func (in *AppGrant) DeepCopy() *AppGrant {
	if in == nil {
		return nil
	}
	out := new(AppGrant)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AppGrant) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AppGrantList) DeepCopyInto(out *AppGrantList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AppGrant, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AppGrantList.
func (in *AppGrantList) DeepCopy() *AppGrantList {
	if in == nil {
		return nil
	}
	out := new(AppGrantList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AppGrantList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AppGrantSpec) DeepCopyInto(out *AppGrantSpec) {
	*out = *in
	if in.Consume != nil {
		in, out := &in.Consume, &out.Consume
		*out = make([]ConsumeGrantSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.AllowConsumers != nil {
		in, out := &in.AllowConsumers, &out.AllowConsumers
		*out = make([]AllowConsumerSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AppGrantSpec.
func (in *AppGrantSpec) DeepCopy() *AppGrantSpec {
	if in == nil {
		return nil
	}
	out := new(AppGrantSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AppGrantStatus) DeepCopyInto(out *AppGrantStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AppGrantStatus.
func (in *AppGrantStatus) DeepCopy() *AppGrantStatus {
	if in == nil {
		return nil
	}
	out := new(AppGrantStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AppPostInstallJob) DeepCopyInto(out *AppPostInstallJob) {
	*out = *in
	if in.EnvFrom != nil {
		in, out := &in.EnvFrom, &out.EnvFrom
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ReadOnlyPVC != nil {
		in, out := &in.ReadOnlyPVC, &out.ReadOnlyPVC
		*out = new(PostInstallJobPVCMount)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AppPostInstallJob.
func (in *AppPostInstallJob) DeepCopy() *AppPostInstallJob {
	if in == nil {
		return nil
	}
	out := new(AppPostInstallJob)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AppProfile) DeepCopyInto(out *AppProfile) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AppProfile.
func (in *AppProfile) DeepCopy() *AppProfile {
	if in == nil {
		return nil
	}
	out := new(AppProfile)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AppProfile) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AppProfileList) DeepCopyInto(out *AppProfileList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AppProfile, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AppProfileList.
func (in *AppProfileList) DeepCopy() *AppProfileList {
	if in == nil {
		return nil
	}
	out := new(AppProfileList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AppProfileList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AppProfileSpec) DeepCopyInto(out *AppProfileSpec) {
	*out = *in
	if in.Categories != nil {
		in, out := &in.Categories, &out.Categories
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Keywords != nil {
		in, out := &in.Keywords, &out.Keywords
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Tile != nil {
		in, out := &in.Tile, &out.Tile
		*out = new(TileSpec)
		**out = **in
	}
	if in.BrowserProxy != nil {
		in, out := &in.BrowserProxy, &out.BrowserProxy
		*out = make([]BrowserProxyRoute, len(*in))
		copy(*out, *in)
	}
	if in.KernelRequirements != nil {
		in, out := &in.KernelRequirements, &out.KernelRequirements
		*out = new(KernelRequirements)
		(*in).DeepCopyInto(*out)
	}
	if in.Provides != nil {
		in, out := &in.Provides, &out.Provides
		*out = make([]ContractRef, len(*in))
		copy(*out, *in)
	}
	if in.OptionalIntegrations != nil {
		in, out := &in.OptionalIntegrations, &out.OptionalIntegrations
		*out = make([]IntegrationRef, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	out.Chart = in.Chart
	if in.ValueMapping != nil {
		in, out := &in.ValueMapping, &out.ValueMapping
		*out = new(ValueMapping)
		(*in).DeepCopyInto(*out)
	}
	if in.AppSecrets != nil {
		in, out := &in.AppSecrets, &out.AppSecrets
		*out = make([]AppSecret, len(*in))
		copy(*out, *in)
	}
	if in.ExtraValues != nil {
		in, out := &in.ExtraValues, &out.ExtraValues
		*out = new(runtime.RawExtension)
		(*in).DeepCopyInto(*out)
	}
	if in.APIIntegration != nil {
		in, out := &in.APIIntegration, &out.APIIntegration
		*out = new(APIIntegration)
		**out = **in
	}
	if in.Ingress != nil {
		in, out := &in.Ingress, &out.Ingress
		*out = new(IngressSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.AdditionalIngresses != nil {
		in, out := &in.AdditionalIngresses, &out.AdditionalIngresses
		*out = make([]IngressSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Sidecars != nil {
		in, out := &in.Sidecars, &out.Sidecars
		*out = make([]AppSidecarSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.PostInstallJob != nil {
		in, out := &in.PostInstallJob, &out.PostInstallJob
		*out = new(AppPostInstallJob)
		(*in).DeepCopyInto(*out)
	}
	if in.PortalTiles != nil {
		in, out := &in.PortalTiles, &out.PortalTiles
		*out = make([]PortalTileSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Provisioning != nil {
		in, out := &in.Provisioning, &out.Provisioning
		*out = new(ProvisioningSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Security != nil {
		in, out := &in.Security, &out.Security
		*out = new(SecuritySpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AppProfileSpec.
func (in *AppProfileSpec) DeepCopy() *AppProfileSpec {
	if in == nil {
		return nil
	}
	out := new(AppProfileSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AppSecret) DeepCopyInto(out *AppSecret) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AppSecret.
func (in *AppSecret) DeepCopy() *AppSecret {
	if in == nil {
		return nil
	}
	out := new(AppSecret)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AppSidecarSpec) DeepCopyInto(out *AppSidecarSpec) {
	*out = *in
	out.Chart = in.Chart
	if in.KernelRequirements != nil {
		in, out := &in.KernelRequirements, &out.KernelRequirements
		*out = new(KernelRequirements)
		(*in).DeepCopyInto(*out)
	}
	if in.AppSecrets != nil {
		in, out := &in.AppSecrets, &out.AppSecrets
		*out = make([]AppSecret, len(*in))
		copy(*out, *in)
	}
	if in.ExtraValues != nil {
		in, out := &in.ExtraValues, &out.ExtraValues
		*out = new(runtime.RawExtension)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AppSidecarSpec.
func (in *AppSidecarSpec) DeepCopy() *AppSidecarSpec {
	if in == nil {
		return nil
	}
	out := new(AppSidecarSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BindingAuth) DeepCopyInto(out *BindingAuth) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BindingAuth.
func (in *BindingAuth) DeepCopy() *BindingAuth {
	if in == nil {
		return nil
	}
	out := new(BindingAuth)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BrowserProxyRoute) DeepCopyInto(out *BrowserProxyRoute) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BrowserProxyRoute.
func (in *BrowserProxyRoute) DeepCopy() *BrowserProxyRoute {
	if in == nil {
		return nil
	}
	out := new(BrowserProxyRoute)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CacheRequirement) DeepCopyInto(out *CacheRequirement) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CacheRequirement.
func (in *CacheRequirement) DeepCopy() *CacheRequirement {
	if in == nil {
		return nil
	}
	out := new(CacheRequirement)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CacheValueMapping) DeepCopyInto(out *CacheValueMapping) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CacheValueMapping.
func (in *CacheValueMapping) DeepCopy() *CacheValueMapping {
	if in == nil {
		return nil
	}
	out := new(CacheValueMapping)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CatalogueEntry) DeepCopyInto(out *CatalogueEntry) {
	*out = *in
	if in.KernelRequirements != nil {
		in, out := &in.KernelRequirements, &out.KernelRequirements
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CatalogueEntry.
func (in *CatalogueEntry) DeepCopy() *CatalogueEntry {
	if in == nil {
		return nil
	}
	out := new(CatalogueEntry)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ChartRef) DeepCopyInto(out *ChartRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ChartRef.
func (in *ChartRef) DeepCopy() *ChartRef {
	if in == nil {
		return nil
	}
	out := new(ChartRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConsumeGrantSpec) DeepCopyInto(out *ConsumeGrantSpec) {
	*out = *in
	if in.Granted != nil {
		in, out := &in.Granted, &out.Granted
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConsumeGrantSpec.
func (in *ConsumeGrantSpec) DeepCopy() *ConsumeGrantSpec {
	if in == nil {
		return nil
	}
	out := new(ConsumeGrantSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContractRef) DeepCopyInto(out *ContractRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContractRef.
func (in *ContractRef) DeepCopy() *ContractRef {
	if in == nil {
		return nil
	}
	out := new(ContractRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatabaseRequirement) DeepCopyInto(out *DatabaseRequirement) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatabaseRequirement.
func (in *DatabaseRequirement) DeepCopy() *DatabaseRequirement {
	if in == nil {
		return nil
	}
	out := new(DatabaseRequirement)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatabaseValueMapping) DeepCopyInto(out *DatabaseValueMapping) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatabaseValueMapping.
func (in *DatabaseValueMapping) DeepCopy() *DatabaseValueMapping {
	if in == nil {
		return nil
	}
	out := new(DatabaseValueMapping)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FilesRequirement) DeepCopyInto(out *FilesRequirement) {
	*out = *in
	if in.Capabilities != nil {
		in, out := &in.Capabilities, &out.Capabilities
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FilesRequirement.
func (in *FilesRequirement) DeepCopy() *FilesRequirement {
	if in == nil {
		return nil
	}
	out := new(FilesRequirement)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GatewayAPIBackend) DeepCopyInto(out *GatewayAPIBackend) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GatewayAPIBackend.
func (in *GatewayAPIBackend) DeepCopy() *GatewayAPIBackend {
	if in == nil {
		return nil
	}
	out := new(GatewayAPIBackend)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GatewayFrameAncestorsSpec) DeepCopyInto(out *GatewayFrameAncestorsSpec) {
	*out = *in
	if in.Origins != nil {
		in, out := &in.Origins, &out.Origins
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GatewayFrameAncestorsSpec.
func (in *GatewayFrameAncestorsSpec) DeepCopy() *GatewayFrameAncestorsSpec {
	if in == nil {
		return nil
	}
	out := new(GatewayFrameAncestorsSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IMAPRequirement) DeepCopyInto(out *IMAPRequirement) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IMAPRequirement.
func (in *IMAPRequirement) DeepCopy() *IMAPRequirement {
	if in == nil {
		return nil
	}
	out := new(IMAPRequirement)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IMAPValueMapping) DeepCopyInto(out *IMAPValueMapping) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IMAPValueMapping.
func (in *IMAPValueMapping) DeepCopy() *IMAPValueMapping {
	if in == nil {
		return nil
	}
	out := new(IMAPValueMapping)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IdentityRequirement) DeepCopyInto(out *IdentityRequirement) {
	*out = *in
	if in.OIDC != nil {
		in, out := &in.OIDC, &out.OIDC
		*out = new(OIDCClientSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.SAML != nil {
		in, out := &in.SAML, &out.SAML
		*out = new(SAMLClientSpec)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IdentityRequirement.
func (in *IdentityRequirement) DeepCopy() *IdentityRequirement {
	if in == nil {
		return nil
	}
	out := new(IdentityRequirement)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IngressSpec) DeepCopyInto(out *IngressSpec) {
	*out = *in
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IngressSpec.
func (in *IngressSpec) DeepCopy() *IngressSpec {
	if in == nil {
		return nil
	}
	out := new(IngressSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IntegrationBinding) DeepCopyInto(out *IntegrationBinding) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IntegrationBinding.
func (in *IntegrationBinding) DeepCopy() *IntegrationBinding {
	if in == nil {
		return nil
	}
	out := new(IntegrationBinding)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *IntegrationBinding) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IntegrationBindingList) DeepCopyInto(out *IntegrationBindingList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]IntegrationBinding, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IntegrationBindingList.
func (in *IntegrationBindingList) DeepCopy() *IntegrationBindingList {
	if in == nil {
		return nil
	}
	out := new(IntegrationBindingList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *IntegrationBindingList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IntegrationBindingSpec) DeepCopyInto(out *IntegrationBindingSpec) {
	*out = *in
	out.Provider = in.Provider
	out.Consumer = in.Consumer
	if in.Capabilities != nil {
		in, out := &in.Capabilities, &out.Capabilities
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Auth != nil {
		in, out := &in.Auth, &out.Auth
		*out = new(BindingAuth)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IntegrationBindingSpec.
func (in *IntegrationBindingSpec) DeepCopy() *IntegrationBindingSpec {
	if in == nil {
		return nil
	}
	out := new(IntegrationBindingSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IntegrationBindingStatus) DeepCopyInto(out *IntegrationBindingStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.SecretRef != nil {
		in, out := &in.SecretRef, &out.SecretRef
		*out = new(LocalSecretRef)
		**out = **in
	}
	if in.LastRotation != nil {
		in, out := &in.LastRotation, &out.LastRotation
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IntegrationBindingStatus.
func (in *IntegrationBindingStatus) DeepCopy() *IntegrationBindingStatus {
	if in == nil {
		return nil
	}
	out := new(IntegrationBindingStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IntegrationRef) DeepCopyInto(out *IntegrationRef) {
	*out = *in
	if in.Capabilities != nil {
		in, out := &in.Capabilities, &out.Capabilities
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IntegrationRef.
func (in *IntegrationRef) DeepCopy() *IntegrationRef {
	if in == nil {
		return nil
	}
	out := new(IntegrationRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IntegrationValueMapping) DeepCopyInto(out *IntegrationValueMapping) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IntegrationValueMapping.
func (in *IntegrationValueMapping) DeepCopy() *IntegrationValueMapping {
	if in == nil {
		return nil
	}
	out := new(IntegrationValueMapping)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KernelRequirements) DeepCopyInto(out *KernelRequirements) {
	*out = *in
	if in.Identity != nil {
		in, out := &in.Identity, &out.Identity
		*out = new(IdentityRequirement)
		(*in).DeepCopyInto(*out)
	}
	if in.Database != nil {
		in, out := &in.Database, &out.Database
		*out = new(DatabaseRequirement)
		**out = **in
	}
	if in.Storage != nil {
		in, out := &in.Storage, &out.Storage
		*out = new(StorageRequirement)
		(*in).DeepCopyInto(*out)
	}
	if in.Cache != nil {
		in, out := &in.Cache, &out.Cache
		*out = new(CacheRequirement)
		**out = **in
	}
	if in.Mail != nil {
		in, out := &in.Mail, &out.Mail
		*out = new(MailRequirement)
		(*in).DeepCopyInto(*out)
	}
	if in.MCP != nil {
		in, out := &in.MCP, &out.MCP
		*out = new(MCPRequirement)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KernelRequirements.
func (in *KernelRequirements) DeepCopy() *KernelRequirements {
	if in == nil {
		return nil
	}
	out := new(KernelRequirements)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LocalSecretRef) DeepCopyInto(out *LocalSecretRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LocalSecretRef.
func (in *LocalSecretRef) DeepCopy() *LocalSecretRef {
	if in == nil {
		return nil
	}
	out := new(LocalSecretRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MCPRequirement) DeepCopyInto(out *MCPRequirement) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MCPRequirement.
func (in *MCPRequirement) DeepCopy() *MCPRequirement {
	if in == nil {
		return nil
	}
	out := new(MCPRequirement)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MacWaiverRequest) DeepCopyInto(out *MacWaiverRequest) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MacWaiverRequest.
func (in *MacWaiverRequest) DeepCopy() *MacWaiverRequest {
	if in == nil {
		return nil
	}
	out := new(MacWaiverRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MailRequirement) DeepCopyInto(out *MailRequirement) {
	*out = *in
	if in.SMTP != nil {
		in, out := &in.SMTP, &out.SMTP
		*out = new(SMTPRequirement)
		**out = **in
	}
	if in.IMAP != nil {
		in, out := &in.IMAP, &out.IMAP
		*out = new(IMAPRequirement)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MailRequirement.
func (in *MailRequirement) DeepCopy() *MailRequirement {
	if in == nil {
		return nil
	}
	out := new(MailRequirement)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OIDCClientSpec) DeepCopyInto(out *OIDCClientSpec) {
	*out = *in
	if in.RedirectURIs != nil {
		in, out := &in.RedirectURIs, &out.RedirectURIs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.PostLogoutRedirectURIs != nil {
		in, out := &in.PostLogoutRedirectURIs, &out.PostLogoutRedirectURIs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OIDCClientSpec.
func (in *OIDCClientSpec) DeepCopy() *OIDCClientSpec {
	if in == nil {
		return nil
	}
	out := new(OIDCClientSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OIDCMapperTemplate) DeepCopyInto(out *OIDCMapperTemplate) {
	*out = *in
	if in.Config != nil {
		in, out := &in.Config, &out.Config
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OIDCMapperTemplate.
func (in *OIDCMapperTemplate) DeepCopy() *OIDCMapperTemplate {
	if in == nil {
		return nil
	}
	out := new(OIDCMapperTemplate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OIDCPackCatalog) DeepCopyInto(out *OIDCPackCatalog) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OIDCPackCatalog.
func (in *OIDCPackCatalog) DeepCopy() *OIDCPackCatalog {
	if in == nil {
		return nil
	}
	out := new(OIDCPackCatalog)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OIDCPackCatalog) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OIDCPackCatalogList) DeepCopyInto(out *OIDCPackCatalogList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]OIDCPackCatalog, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OIDCPackCatalogList.
func (in *OIDCPackCatalogList) DeepCopy() *OIDCPackCatalogList {
	if in == nil {
		return nil
	}
	out := new(OIDCPackCatalogList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OIDCPackCatalogList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OIDCPackCatalogSpec) DeepCopyInto(out *OIDCPackCatalogSpec) {
	*out = *in
	if in.MapperTemplates != nil {
		in, out := &in.MapperTemplates, &out.MapperTemplates
		*out = make(map[string]OIDCMapperTemplate, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	if in.Packs != nil {
		in, out := &in.Packs, &out.Packs
		*out = make(map[string]OIDCPackSpec, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	if in.ExtraManagedByAttributeGroups != nil {
		in, out := &in.ExtraManagedByAttributeGroups, &out.ExtraManagedByAttributeGroups
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OIDCPackCatalogSpec.
func (in *OIDCPackCatalogSpec) DeepCopy() *OIDCPackCatalogSpec {
	if in == nil {
		return nil
	}
	out := new(OIDCPackCatalogSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OIDCPackCatalogStatus) DeepCopyInto(out *OIDCPackCatalogStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OIDCPackCatalogStatus.
func (in *OIDCPackCatalogStatus) DeepCopy() *OIDCPackCatalogStatus {
	if in == nil {
		return nil
	}
	out := new(OIDCPackCatalogStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OIDCPackSpec) DeepCopyInto(out *OIDCPackSpec) {
	*out = *in
	if in.DefaultScopes != nil {
		in, out := &in.DefaultScopes, &out.DefaultScopes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Mappers != nil {
		in, out := &in.Mappers, &out.Mappers
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OIDCPackSpec.
func (in *OIDCPackSpec) DeepCopy() *OIDCPackSpec {
	if in == nil {
		return nil
	}
	out := new(OIDCPackSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OIDCValueMapping) DeepCopyInto(out *OIDCValueMapping) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OIDCValueMapping.
func (in *OIDCValueMapping) DeepCopy() *OIDCValueMapping {
	if in == nil {
		return nil
	}
	out := new(OIDCValueMapping)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PlatformSecurityPolicy) DeepCopyInto(out *PlatformSecurityPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PlatformSecurityPolicy.
func (in *PlatformSecurityPolicy) DeepCopy() *PlatformSecurityPolicy {
	if in == nil {
		return nil
	}
	out := new(PlatformSecurityPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PlatformSecurityPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PlatformSecurityPolicyList) DeepCopyInto(out *PlatformSecurityPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PlatformSecurityPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PlatformSecurityPolicyList.
func (in *PlatformSecurityPolicyList) DeepCopy() *PlatformSecurityPolicyList {
	if in == nil {
		return nil
	}
	out := new(PlatformSecurityPolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PlatformSecurityPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PlatformSecurityPolicySpec) DeepCopyInto(out *PlatformSecurityPolicySpec) {
	*out = *in
	if in.AllowedMacWaivers != nil {
		in, out := &in.AllowedMacWaivers, &out.AllowedMacWaivers
		*out = make([]AllowedMacWaiver, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PlatformSecurityPolicySpec.
func (in *PlatformSecurityPolicySpec) DeepCopy() *PlatformSecurityPolicySpec {
	if in == nil {
		return nil
	}
	out := new(PlatformSecurityPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PlatformSecurityPolicyStatus) DeepCopyInto(out *PlatformSecurityPolicyStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PlatformSecurityPolicyStatus.
func (in *PlatformSecurityPolicyStatus) DeepCopy() *PlatformSecurityPolicyStatus {
	if in == nil {
		return nil
	}
	out := new(PlatformSecurityPolicyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PortalTileSpec) DeepCopyInto(out *PortalTileSpec) {
	*out = *in
	if in.DisplayName != nil {
		in, out := &in.DisplayName, &out.DisplayName
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Tile != nil {
		in, out := &in.Tile, &out.Tile
		*out = new(TileSpec)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PortalTileSpec.
func (in *PortalTileSpec) DeepCopy() *PortalTileSpec {
	if in == nil {
		return nil
	}
	out := new(PortalTileSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PostInstallJobPVCMount) DeepCopyInto(out *PostInstallJobPVCMount) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PostInstallJobPVCMount.
func (in *PostInstallJobPVCMount) DeepCopy() *PostInstallJobPVCMount {
	if in == nil {
		return nil
	}
	out := new(PostInstallJobPVCMount)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PrivilegedRoleSpec) DeepCopyInto(out *PrivilegedRoleSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PrivilegedRoleSpec.
func (in *PrivilegedRoleSpec) DeepCopy() *PrivilegedRoleSpec {
	if in == nil {
		return nil
	}
	out := new(PrivilegedRoleSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProfileIdentity) DeepCopyInto(out *ProfileIdentity) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProfileIdentity.
func (in *ProfileIdentity) DeepCopy() *ProfileIdentity {
	if in == nil {
		return nil
	}
	out := new(ProfileIdentity)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProfileReference) DeepCopyInto(out *ProfileReference) {
	*out = *in
	if in.Identity != nil {
		in, out := &in.Identity, &out.Identity
		*out = new(ProfileIdentity)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProfileReference.
func (in *ProfileReference) DeepCopy() *ProfileReference {
	if in == nil {
		return nil
	}
	out := new(ProfileReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProvisioningSpec) DeepCopyInto(out *ProvisioningSpec) {
	*out = *in
	if in.PrivilegedRole != nil {
		in, out := &in.PrivilegedRole, &out.PrivilegedRole
		*out = new(PrivilegedRoleSpec)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProvisioningSpec.
func (in *ProvisioningSpec) DeepCopy() *ProvisioningSpec {
	if in == nil {
		return nil
	}
	out := new(ProvisioningSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *S3Requirement) DeepCopyInto(out *S3Requirement) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new S3Requirement.
func (in *S3Requirement) DeepCopy() *S3Requirement {
	if in == nil {
		return nil
	}
	out := new(S3Requirement)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *S3ValueMapping) DeepCopyInto(out *S3ValueMapping) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new S3ValueMapping.
func (in *S3ValueMapping) DeepCopy() *S3ValueMapping {
	if in == nil {
		return nil
	}
	out := new(S3ValueMapping)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SAMLClientSpec) DeepCopyInto(out *SAMLClientSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SAMLClientSpec.
func (in *SAMLClientSpec) DeepCopy() *SAMLClientSpec {
	if in == nil {
		return nil
	}
	out := new(SAMLClientSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SMTPRequirement) DeepCopyInto(out *SMTPRequirement) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SMTPRequirement.
func (in *SMTPRequirement) DeepCopy() *SMTPRequirement {
	if in == nil {
		return nil
	}
	out := new(SMTPRequirement)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SMTPValueMapping) DeepCopyInto(out *SMTPValueMapping) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SMTPValueMapping.
func (in *SMTPValueMapping) DeepCopy() *SMTPValueMapping {
	if in == nil {
		return nil
	}
	out := new(SMTPValueMapping)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecuritySpec) DeepCopyInto(out *SecuritySpec) {
	*out = *in
	if in.MacWaivers != nil {
		in, out := &in.MacWaivers, &out.MacWaivers
		*out = make([]MacWaiverRequest, len(*in))
		copy(*out, *in)
	}
	if in.Egress != nil {
		in, out := &in.Egress, &out.Egress
		*out = make([]networkingv1.NetworkPolicyEgressRule, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecuritySpec.
func (in *SecuritySpec) DeepCopy() *SecuritySpec {
	if in == nil {
		return nil
	}
	out := new(SecuritySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StorageRequirement) DeepCopyInto(out *StorageRequirement) {
	*out = *in
	if in.S3 != nil {
		in, out := &in.S3, &out.S3
		*out = new(S3Requirement)
		**out = **in
	}
	if in.Files != nil {
		in, out := &in.Files, &out.Files
		*out = new(FilesRequirement)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StorageRequirement.
func (in *StorageRequirement) DeepCopy() *StorageRequirement {
	if in == nil {
		return nil
	}
	out := new(StorageRequirement)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Tenant) DeepCopyInto(out *Tenant) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Tenant.
func (in *Tenant) DeepCopy() *Tenant {
	if in == nil {
		return nil
	}
	out := new(Tenant)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Tenant) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TenantApp) DeepCopyInto(out *TenantApp) {
	*out = *in
	if in.ProfileRef != nil {
		in, out := &in.ProfileRef, &out.ProfileRef
		*out = new(ProfileReference)
		(*in).DeepCopyInto(*out)
	}
	if in.Config != nil {
		in, out := &in.Config, &out.Config
		*out = new(TenantAppConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TenantApp.
func (in *TenantApp) DeepCopy() *TenantApp {
	if in == nil {
		return nil
	}
	out := new(TenantApp)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TenantAppConfig) DeepCopyInto(out *TenantAppConfig) {
	*out = *in
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(int32)
		**out = **in
	}
	if in.ExtraValues != nil {
		in, out := &in.ExtraValues, &out.ExtraValues
		*out = new(runtime.RawExtension)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TenantAppConfig.
func (in *TenantAppConfig) DeepCopy() *TenantAppConfig {
	if in == nil {
		return nil
	}
	out := new(TenantAppConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TenantIsolation) DeepCopyInto(out *TenantIsolation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TenantIsolation.
func (in *TenantIsolation) DeepCopy() *TenantIsolation {
	if in == nil {
		return nil
	}
	out := new(TenantIsolation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TenantList) DeepCopyInto(out *TenantList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Tenant, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TenantList.
func (in *TenantList) DeepCopy() *TenantList {
	if in == nil {
		return nil
	}
	out := new(TenantList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TenantList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TenantMail) DeepCopyInto(out *TenantMail) {
	*out = *in
	if in.QuotaPerUser != nil {
		in, out := &in.QuotaPerUser, &out.QuotaPerUser
		x := (*in).DeepCopy()
		*out = &x
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TenantMail.
func (in *TenantMail) DeepCopy() *TenantMail {
	if in == nil {
		return nil
	}
	out := new(TenantMail)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TenantMailStatus) DeepCopyInto(out *TenantMailStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TenantMailStatus.
func (in *TenantMailStatus) DeepCopy() *TenantMailStatus {
	if in == nil {
		return nil
	}
	out := new(TenantMailStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TenantQuotas) DeepCopyInto(out *TenantQuotas) {
	*out = *in
	if in.Storage != nil {
		in, out := &in.Storage, &out.Storage
		x := (*in).DeepCopy()
		*out = &x
	}
	if in.CPU != nil {
		in, out := &in.CPU, &out.CPU
		x := (*in).DeepCopy()
		*out = &x
	}
	if in.Memory != nil {
		in, out := &in.Memory, &out.Memory
		x := (*in).DeepCopy()
		*out = &x
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TenantQuotas.
func (in *TenantQuotas) DeepCopy() *TenantQuotas {
	if in == nil {
		return nil
	}
	out := new(TenantQuotas)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TenantSpec) DeepCopyInto(out *TenantSpec) {
	*out = *in
	if in.Isolation != nil {
		in, out := &in.Isolation, &out.Isolation
		*out = new(TenantIsolation)
		**out = **in
	}
	if in.Mail != nil {
		in, out := &in.Mail, &out.Mail
		*out = new(TenantMail)
		(*in).DeepCopyInto(*out)
	}
	if in.Quotas != nil {
		in, out := &in.Quotas, &out.Quotas
		*out = new(TenantQuotas)
		(*in).DeepCopyInto(*out)
	}
	if in.Apps != nil {
		in, out := &in.Apps, &out.Apps
		*out = make([]TenantApp, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TenantSpec.
func (in *TenantSpec) DeepCopy() *TenantSpec {
	if in == nil {
		return nil
	}
	out := new(TenantSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TenantStatus) DeepCopyInto(out *TenantStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ProvisionedApps != nil {
		in, out := &in.ProvisionedApps, &out.ProvisionedApps
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Mail != nil {
		in, out := &in.Mail, &out.Mail
		*out = new(TenantMailStatus)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TenantStatus.
func (in *TenantStatus) DeepCopy() *TenantStatus {
	if in == nil {
		return nil
	}
	out := new(TenantStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TileSpec) DeepCopyInto(out *TileSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TileSpec.
func (in *TileSpec) DeepCopy() *TileSpec {
	if in == nil {
		return nil
	}
	out := new(TileSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ValueMapping) DeepCopyInto(out *ValueMapping) {
	*out = *in
	if in.OIDC != nil {
		in, out := &in.OIDC, &out.OIDC
		*out = new(OIDCValueMapping)
		**out = **in
	}
	if in.Database != nil {
		in, out := &in.Database, &out.Database
		*out = new(DatabaseValueMapping)
		**out = **in
	}
	if in.S3 != nil {
		in, out := &in.S3, &out.S3
		*out = new(S3ValueMapping)
		**out = **in
	}
	if in.Cache != nil {
		in, out := &in.Cache, &out.Cache
		*out = new(CacheValueMapping)
		**out = **in
	}
	if in.SMTP != nil {
		in, out := &in.SMTP, &out.SMTP
		*out = new(SMTPValueMapping)
		**out = **in
	}
	if in.IMAP != nil {
		in, out := &in.IMAP, &out.IMAP
		*out = new(IMAPValueMapping)
		**out = **in
	}
	if in.Integrations != nil {
		in, out := &in.Integrations, &out.Integrations
		*out = make(map[string]IntegrationValueMapping, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ValueMapping.
func (in *ValueMapping) DeepCopy() *ValueMapping {
	if in == nil {
		return nil
	}
	out := new(ValueMapping)
	in.DeepCopyInto(out)
	return out
}
