//go:build !ignore_autogenerated

/*
Copyright 2026 Gentian Organization.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	networkingv1 "k8s.io/api/networking/v1"
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *APIIntegration) DeepCopyInto(out *APIIntegration) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new APIIntegration.
func (in *APIIntegration) DeepCopy() *APIIntegration {
	if in == nil {
		return nil
	}
	out := new(APIIntegration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AllowConsumerSpec) DeepCopyInto(out *AllowConsumerSpec) {
	*out = *in
	if in.Scope != nil {
		in, out := &in.Scope, &out.Scope
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AllowConsumerSpec.
func (in *AllowConsumerSpec) DeepCopy() *AllowConsumerSpec {
	if in == nil {
		return nil
	}
	out := new(AllowConsumerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AllowedMacWaiver) DeepCopyInto(out *AllowedMacWaiver) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AllowedMacWaiver.
func (in *AllowedMacWaiver) DeepCopy() *AllowedMacWaiver {
	if in == nil {
		return nil
	}
	out := new(AllowedMacWaiver)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AppCatalogue) DeepCopyInto(out *AppCatalogue) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AppCatalogue.
func (in *AppCatalogue) DeepCopy() *AppCatalogue {
	if in == nil {
		return nil
	}
	out := new(AppCatalogue)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AppCatalogue) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AppCatalogueList) DeepCopyInto(out *AppCatalogueList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AppCatalogue, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AppCatalogueList.
func (in *AppCatalogueList) DeepCopy() *AppCatalogueList {
	if in == nil {
		return nil
	}
	out := new(AppCatalogueList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AppCatalogueList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AppCatalogueSpec) DeepCopyInto(out *AppCatalogueSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AppCatalogueSpec.
func (in *AppCatalogueSpec) DeepCopy() *AppCatalogueSpec {
	if in == nil {
		return nil
	}
	out := new(AppCatalogueSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AppCatalogueStatus) DeepCopyInto(out *AppCatalogueStatus) {
	*out = *in
	if in.Apps != nil {
		in, out := &in.Apps, &out.Apps
		*out = make([]CatalogueEntry, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.LastUpdated != nil {
		in, out := &in.LastUpdated, &out.LastUpdated
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AppCatalogueStatus.
func (in *AppCatalogueStatus) DeepCopy() *AppCatalogueStatus {
	if in == nil {
		return nil
	}
	out := new(AppCatalogueStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AppEndpoint) DeepCopyInto(out *AppEndpoint) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AppEndpoint.
func (in *AppEndpoint) DeepCopy() *AppEndpoint {
	if in == nil {
		return nil
	}
	out := new(AppEndpoint)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AppExportStatus) DeepCopyInto(out *AppExportStatus) {
	*out = *in
	if in.Stores != nil {
		in, out := &in.Stores, &out.Stores
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.QuiesceStart != nil {
		in, out := &in.QuiesceStart, &out.QuiesceStart
		*out = (*in).DeepCopy()
	}
	if in.QuiesceEnd != nil {
		in, out := &in.QuiesceEnd, &out.QuiesceEnd
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AppExportStatus.
func (in *AppExportStatus) DeepCopy() *AppExportStatus {
	if in == nil {
		return nil
	}
	out := new(AppExportStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AppGrant) DeepCopyInto(out *AppGrant) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AppGrant.
func (in *AppGrant) DeepCopy() *AppGrant {
	if in == nil {
		return nil
	}
	out := new(AppGrant)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AppGrant) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AppGrantList) DeepCopyInto(out *AppGrantList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AppGrant, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AppGrantList.
func (in *AppGrantList) DeepCopy() *AppGrantList {
	if in == nil {
		return nil
	}
	out := new(AppGrantList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AppGrantList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AppGrantSpec) DeepCopyInto(out *AppGrantSpec) {
	*out = *in
	if in.Consume != nil {
		in, out := &in.Consume, &out.Consume
		*out = make([]ConsumeGrantSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.AllowConsumers != nil {
		in, out := &in.AllowConsumers, &out.AllowConsumers
		*out = make([]AllowConsumerSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AppGrantSpec.
func (in *AppGrantSpec) DeepCopy() *AppGrantSpec {
	if in == nil {
		return nil
	}
	out := new(AppGrantSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AppGrantStatus) DeepCopyInto(out *AppGrantStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AppGrantStatus.
func (in *AppGrantStatus) DeepCopy() *AppGrantStatus {
	if in == nil {
		return nil
	}
	out := new(AppGrantStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AppPackage) DeepCopyInto(out *AppPackage) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AppPackage.
func (in *AppPackage) DeepCopy() *AppPackage {
	if in == nil {
		return nil
	}
	out := new(AppPackage)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AppPackage) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AppPackageList) DeepCopyInto(out *AppPackageList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AppPackage, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AppPackageList.
func (in *AppPackageList) DeepCopy() *AppPackageList {
	if in == nil {
		return nil
	}
	out := new(AppPackageList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AppPackageList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AppPackageSpec) DeepCopyInto(out *AppPackageSpec) {
	*out = *in
	if in.Addons != nil {
		in, out := &in.Addons, &out.Addons
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Tile != nil {
		in, out := &in.Tile, &out.Tile
		*out = new(TileSpec)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AppPackageSpec.
func (in *AppPackageSpec) DeepCopy() *AppPackageSpec {
	if in == nil {
		return nil
	}
	out := new(AppPackageSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AppPostInstallJob) DeepCopyInto(out *AppPostInstallJob) {
	*out = *in
	if in.EnvFrom != nil {
		in, out := &in.EnvFrom, &out.EnvFrom
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ReadOnlyPVC != nil {
		in, out := &in.ReadOnlyPVC, &out.ReadOnlyPVC
		*out = new(PostInstallJobPVCMount)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AppPostInstallJob.
func (in *AppPostInstallJob) DeepCopy() *AppPostInstallJob {
	if in == nil {
		return nil
	}
	out := new(AppPostInstallJob)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AppProfile) DeepCopyInto(out *AppProfile) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AppProfile.
func (in *AppProfile) DeepCopy() *AppProfile {
	if in == nil {
		return nil
	}
	out := new(AppProfile)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AppProfile) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AppProfileList) DeepCopyInto(out *AppProfileList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AppProfile, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AppProfileList.
func (in *AppProfileList) DeepCopy() *AppProfileList {
	if in == nil {
		return nil
	}
	out := new(AppProfileList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AppProfileList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AppProfileSpec) DeepCopyInto(out *AppProfileSpec) {
	*out = *in
	if in.Categories != nil {
		in, out := &in.Categories, &out.Categories
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Keywords != nil {
		in, out := &in.Keywords, &out.Keywords
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Tile != nil {
		in, out := &in.Tile, &out.Tile
		*out = new(TileSpec)
		**out = **in
	}
	if in.BrowserProxy != nil {
		in, out := &in.BrowserProxy, &out.BrowserProxy
		*out = make([]BrowserProxyRoute, len(*in))
		copy(*out, *in)
	}
	if in.KernelRequirements != nil {
		in, out := &in.KernelRequirements, &out.KernelRequirements
		*out = new(KernelRequirements)
		(*in).DeepCopyInto(*out)
	}
	if in.Backup != nil {
		in, out := &in.Backup, &out.Backup
		*out = new(BackupSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Provides != nil {
		in, out := &in.Provides, &out.Provides
		*out = make([]ContractRef, len(*in))
		copy(*out, *in)
	}
	if in.OptionalIntegrations != nil {
		in, out := &in.OptionalIntegrations, &out.OptionalIntegrations
		*out = make([]IntegrationRef, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	out.Chart = in.Chart
	if in.ValueMapping != nil {
		in, out := &in.ValueMapping, &out.ValueMapping
		*out = new(ValueMapping)
		(*in).DeepCopyInto(*out)
	}
	if in.AppSecrets != nil {
		in, out := &in.AppSecrets, &out.AppSecrets
		*out = make([]AppSecret, len(*in))
		copy(*out, *in)
	}
	if in.DerivedSecretKeys != nil {
		in, out := &in.DerivedSecretKeys, &out.DerivedSecretKeys
		*out = make([]DerivedSecretKey, len(*in))
		copy(*out, *in)
	}
	if in.ExtraValues != nil {
		in, out := &in.ExtraValues, &out.ExtraValues
		*out = new(runtime.RawExtension)
		(*in).DeepCopyInto(*out)
	}
	if in.APIIntegration != nil {
		in, out := &in.APIIntegration, &out.APIIntegration
		*out = new(APIIntegration)
		**out = **in
	}
	if in.Ingress != nil {
		in, out := &in.Ingress, &out.Ingress
		*out = new(IngressSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.AdditionalIngresses != nil {
		in, out := &in.AdditionalIngresses, &out.AdditionalIngresses
		*out = make([]IngressSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Sidecars != nil {
		in, out := &in.Sidecars, &out.Sidecars
		*out = make([]AppSidecarSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.PostInstallJob != nil {
		in, out := &in.PostInstallJob, &out.PostInstallJob
		*out = new(AppPostInstallJob)
		(*in).DeepCopyInto(*out)
	}
	if in.PortalTiles != nil {
		in, out := &in.PortalTiles, &out.PortalTiles
		*out = make([]PortalTileSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Provisioning != nil {
		in, out := &in.Provisioning, &out.Provisioning
		*out = new(ProvisioningSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Security != nil {
		in, out := &in.Security, &out.Security
		*out = new(SecuritySpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Customization != nil {
		in, out := &in.Customization, &out.Customization
		*out = new(CustomizationSurface)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AppProfileSpec.
func (in *AppProfileSpec) DeepCopy() *AppProfileSpec {
	if in == nil {
		return nil
	}
	out := new(AppProfileSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AppSecret) DeepCopyInto(out *AppSecret) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AppSecret.
func (in *AppSecret) DeepCopy() *AppSecret {
	if in == nil {
		return nil
	}
	out := new(AppSecret)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AppSidecarSpec) DeepCopyInto(out *AppSidecarSpec) {
	*out = *in
	out.Chart = in.Chart
	if in.KernelRequirements != nil {
		in, out := &in.KernelRequirements, &out.KernelRequirements
		*out = new(KernelRequirements)
		(*in).DeepCopyInto(*out)
	}
	if in.AppSecrets != nil {
		in, out := &in.AppSecrets, &out.AppSecrets
		*out = make([]AppSecret, len(*in))
		copy(*out, *in)
	}
	if in.ExtraValues != nil {
		in, out := &in.ExtraValues, &out.ExtraValues
		*out = new(runtime.RawExtension)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AppSidecarSpec.
func (in *AppSidecarSpec) DeepCopy() *AppSidecarSpec {
	if in == nil {
		return nil
	}
	out := new(AppSidecarSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BackupBoundSecret) DeepCopyInto(out *BackupBoundSecret) {
	*out = *in
	if in.Keys != nil {
		in, out := &in.Keys, &out.Keys
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BackupBoundSecret.
func (in *BackupBoundSecret) DeepCopy() *BackupBoundSecret {
	if in == nil {
		return nil
	}
	out := new(BackupBoundSecret)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BackupQuiesce) DeepCopyInto(out *BackupQuiesce) {
	*out = *in
	if in.Pre != nil {
		in, out := &in.Pre, &out.Pre
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Post != nil {
		in, out := &in.Post, &out.Post
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BackupQuiesce.
func (in *BackupQuiesce) DeepCopy() *BackupQuiesce {
	if in == nil {
		return nil
	}
	out := new(BackupQuiesce)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BackupRestore) DeepCopyInto(out *BackupRestore) {
	*out = *in
	if in.Post != nil {
		in, out := &in.Post, &out.Post
		*out = make([][]string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = make([]string, len(*in))
				copy(*out, *in)
			}
		}
	}
	if in.Verify != nil {
		in, out := &in.Verify, &out.Verify
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BackupRestore.
func (in *BackupRestore) DeepCopy() *BackupRestore {
	if in == nil {
		return nil
	}
	out := new(BackupRestore)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BackupSpec) DeepCopyInto(out *BackupSpec) {
	*out = *in
	if in.Quiesce != nil {
		in, out := &in.Quiesce, &out.Quiesce
		*out = new(BackupQuiesce)
		(*in).DeepCopyInto(*out)
	}
	if in.Volumes != nil {
		in, out := &in.Volumes, &out.Volumes
		*out = new(BackupVolumes)
		(*in).DeepCopyInto(*out)
	}
	if in.BoundSecrets != nil {
		in, out := &in.BoundSecrets, &out.BoundSecrets
		*out = make([]BackupBoundSecret, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Restore != nil {
		in, out := &in.Restore, &out.Restore
		*out = new(BackupRestore)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BackupSpec.
func (in *BackupSpec) DeepCopy() *BackupSpec {
	if in == nil {
		return nil
	}
	out := new(BackupSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BackupVolumes) DeepCopyInto(out *BackupVolumes) {
	*out = *in
	if in.Include != nil {
		in, out := &in.Include, &out.Include
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ExcludePaths != nil {
		in, out := &in.ExcludePaths, &out.ExcludePaths
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BackupVolumes.
func (in *BackupVolumes) DeepCopy() *BackupVolumes {
	if in == nil {
		return nil
	}
	out := new(BackupVolumes)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BindingAuth) DeepCopyInto(out *BindingAuth) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BindingAuth.
func (in *BindingAuth) DeepCopy() *BindingAuth {
	if in == nil {
		return nil
	}
	out := new(BindingAuth)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BrowserProxyRoute) DeepCopyInto(out *BrowserProxyRoute) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BrowserProxyRoute.
func (in *BrowserProxyRoute) DeepCopy() *BrowserProxyRoute {
	if in == nil {
		return nil
	}
	out := new(BrowserProxyRoute)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BundleRef) DeepCopyInto(out *BundleRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BundleRef.
func (in *BundleRef) DeepCopy() *BundleRef {
	if in == nil {
		return nil
	}
	out := new(BundleRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CacheRequirement) DeepCopyInto(out *CacheRequirement) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CacheRequirement.
func (in *CacheRequirement) DeepCopy() *CacheRequirement {
	if in == nil {
		return nil
	}
	out := new(CacheRequirement)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CacheValueMapping) DeepCopyInto(out *CacheValueMapping) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CacheValueMapping.
func (in *CacheValueMapping) DeepCopy() *CacheValueMapping {
	if in == nil {
		return nil
	}
	out := new(CacheValueMapping)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CatalogueEntry) DeepCopyInto(out *CatalogueEntry) {
	*out = *in
	if in.KernelRequirements != nil {
		in, out := &in.KernelRequirements, &out.KernelRequirements
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CatalogueEntry.
func (in *CatalogueEntry) DeepCopy() *CatalogueEntry {
	if in == nil {
		return nil
	}
	out := new(CatalogueEntry)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ChartRef) DeepCopyInto(out *ChartRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ChartRef.
func (in *ChartRef) DeepCopy() *ChartRef {
	if in == nil {
		return nil
	}
	out := new(ChartRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConsumeGrantSpec) DeepCopyInto(out *ConsumeGrantSpec) {
	*out = *in
	if in.Granted != nil {
		in, out := &in.Granted, &out.Granted
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConsumeGrantSpec.
func (in *ConsumeGrantSpec) DeepCopy() *ConsumeGrantSpec {
	if in == nil {
		return nil
	}
	out := new(ConsumeGrantSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContractRef) DeepCopyInto(out *ContractRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContractRef.
func (in *ContractRef) DeepCopy() *ContractRef {
	if in == nil {
		return nil
	}
	out := new(ContractRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CredentialConsumer) DeepCopyInto(out *CredentialConsumer) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CredentialConsumer.
func (in *CredentialConsumer) DeepCopy() *CredentialConsumer {
	if in == nil {
		return nil
	}
	out := new(CredentialConsumer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CredentialField) DeepCopyInto(out *CredentialField) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CredentialField.
func (in *CredentialField) DeepCopy() *CredentialField {
	if in == nil {
		return nil
	}
	out := new(CredentialField)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CredentialRequirement) DeepCopyInto(out *CredentialRequirement) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CredentialRequirement.
func (in *CredentialRequirement) DeepCopy() *CredentialRequirement {
	if in == nil {
		return nil
	}
	out := new(CredentialRequirement)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CredentialRequirement) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CredentialRequirementList) DeepCopyInto(out *CredentialRequirementList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CredentialRequirement, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CredentialRequirementList.
func (in *CredentialRequirementList) DeepCopy() *CredentialRequirementList {
	if in == nil {
		return nil
	}
	out := new(CredentialRequirementList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CredentialRequirementList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CredentialRequirementSpec) DeepCopyInto(out *CredentialRequirementSpec) {
	*out = *in
	if in.Fields != nil {
		in, out := &in.Fields, &out.Fields
		*out = make([]CredentialField, len(*in))
		copy(*out, *in)
	}
	if in.Validate != nil {
		in, out := &in.Validate, &out.Validate
		*out = new(CredentialValidation)
		**out = **in
	}
	if in.ConsumedBy != nil {
		in, out := &in.ConsumedBy, &out.ConsumedBy
		*out = make([]CredentialConsumer, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CredentialRequirementSpec.
func (in *CredentialRequirementSpec) DeepCopy() *CredentialRequirementSpec {
	if in == nil {
		return nil
	}
	out := new(CredentialRequirementSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CredentialValidation) DeepCopyInto(out *CredentialValidation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CredentialValidation.
func (in *CredentialValidation) DeepCopy() *CredentialValidation {
	if in == nil {
		return nil
	}
	out := new(CredentialValidation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Customization) DeepCopyInto(out *Customization) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Customization.
func (in *Customization) DeepCopy() *Customization {
	if in == nil {
		return nil
	}
	out := new(Customization)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Customization) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CustomizationAddon) DeepCopyInto(out *CustomizationAddon) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CustomizationAddon.
func (in *CustomizationAddon) DeepCopy() *CustomizationAddon {
	if in == nil {
		return nil
	}
	out := new(CustomizationAddon)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CustomizationAddonActivation) DeepCopyInto(out *CustomizationAddonActivation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CustomizationAddonActivation.
func (in *CustomizationAddonActivation) DeepCopy() *CustomizationAddonActivation {
	if in == nil {
		return nil
	}
	out := new(CustomizationAddonActivation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CustomizationAddonValues) DeepCopyInto(out *CustomizationAddonValues) {
	*out = *in
	if in.Values != nil {
		in, out := &in.Values, &out.Values
		*out = new(runtime.RawExtension)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CustomizationAddonValues.
func (in *CustomizationAddonValues) DeepCopy() *CustomizationAddonValues {
	if in == nil {
		return nil
	}
	out := new(CustomizationAddonValues)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CustomizationArtifact) DeepCopyInto(out *CustomizationArtifact) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CustomizationArtifact.
func (in *CustomizationArtifact) DeepCopy() *CustomizationArtifact {
	if in == nil {
		return nil
	}
	out := new(CustomizationArtifact)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CustomizationConfigure) DeepCopyInto(out *CustomizationConfigure) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CustomizationConfigure.
func (in *CustomizationConfigure) DeepCopy() *CustomizationConfigure {
	if in == nil {
		return nil
	}
	out := new(CustomizationConfigure)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CustomizationDropIn) DeepCopyInto(out *CustomizationDropIn) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CustomizationDropIn.
func (in *CustomizationDropIn) DeepCopy() *CustomizationDropIn {
	if in == nil {
		return nil
	}
	out := new(CustomizationDropIn)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CustomizationExtension) DeepCopyInto(out *CustomizationExtension) {
	*out = *in
	if in.Delivery != nil {
		in, out := &in.Delivery, &out.Delivery
		*out = make([]CustomizationDelivery, len(*in))
		copy(*out, *in)
	}
	if in.TestMatrix != nil {
		in, out := &in.TestMatrix, &out.TestMatrix
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CustomizationExtension.
func (in *CustomizationExtension) DeepCopy() *CustomizationExtension {
	if in == nil {
		return nil
	}
	out := new(CustomizationExtension)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CustomizationFork) DeepCopyInto(out *CustomizationFork) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CustomizationFork.
func (in *CustomizationFork) DeepCopy() *CustomizationFork {
	if in == nil {
		return nil
	}
	out := new(CustomizationFork)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CustomizationLicensing) DeepCopyInto(out *CustomizationLicensing) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CustomizationLicensing.
func (in *CustomizationLicensing) DeepCopy() *CustomizationLicensing {
	if in == nil {
		return nil
	}
	out := new(CustomizationLicensing)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CustomizationList) DeepCopyInto(out *CustomizationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Customization, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CustomizationList.
func (in *CustomizationList) DeepCopy() *CustomizationList {
	if in == nil {
		return nil
	}
	out := new(CustomizationList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CustomizationList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CustomizationOrigin) DeepCopyInto(out *CustomizationOrigin) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CustomizationOrigin.
func (in *CustomizationOrigin) DeepCopy() *CustomizationOrigin {
	if in == nil {
		return nil
	}
	out := new(CustomizationOrigin)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CustomizationPatch) DeepCopyInto(out *CustomizationPatch) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CustomizationPatch.
func (in *CustomizationPatch) DeepCopy() *CustomizationPatch {
	if in == nil {
		return nil
	}
	out := new(CustomizationPatch)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CustomizationPublishedAPI) DeepCopyInto(out *CustomizationPublishedAPI) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CustomizationPublishedAPI.
func (in *CustomizationPublishedAPI) DeepCopy() *CustomizationPublishedAPI {
	if in == nil {
		return nil
	}
	out := new(CustomizationPublishedAPI)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CustomizationPublishes) DeepCopyInto(out *CustomizationPublishes) {
	*out = *in
	if in.APIs != nil {
		in, out := &in.APIs, &out.APIs
		*out = make([]CustomizationPublishedAPI, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CustomizationPublishes.
func (in *CustomizationPublishes) DeepCopy() *CustomizationPublishes {
	if in == nil {
		return nil
	}
	out := new(CustomizationPublishes)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CustomizationRepackage) DeepCopyInto(out *CustomizationRepackage) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CustomizationRepackage.
func (in *CustomizationRepackage) DeepCopy() *CustomizationRepackage {
	if in == nil {
		return nil
	}
	out := new(CustomizationRepackage)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CustomizationSecurity) DeepCopyInto(out *CustomizationSecurity) {
	*out = *in
	if in.MACWaivers != nil {
		in, out := &in.MACWaivers, &out.MACWaivers
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.NewEgress != nil {
		in, out := &in.NewEgress, &out.NewEgress
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CustomizationSecurity.
func (in *CustomizationSecurity) DeepCopy() *CustomizationSecurity {
	if in == nil {
		return nil
	}
	out := new(CustomizationSecurity)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CustomizationSpec) DeepCopyInto(out *CustomizationSpec) {
	*out = *in
	out.Target = in.Target
	if in.Tenants != nil {
		in, out := &in.Tenants, &out.Tenants
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.RungJustification != nil {
		in, out := &in.RungJustification, &out.RungJustification
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.UpstreamFirst != nil {
		in, out := &in.UpstreamFirst, &out.UpstreamFirst
		*out = new(CustomizationUpstreamFirst)
		**out = **in
	}
	if in.Artifacts != nil {
		in, out := &in.Artifacts, &out.Artifacts
		*out = make([]CustomizationArtifact, len(*in))
		copy(*out, *in)
	}
	if in.Origin != nil {
		in, out := &in.Origin, &out.Origin
		*out = new(CustomizationOrigin)
		**out = **in
	}
	if in.TestedAgainst != nil {
		in, out := &in.TestedAgainst, &out.TestedAgainst
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Tests != nil {
		in, out := &in.Tests, &out.Tests
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Security != nil {
		in, out := &in.Security, &out.Security
		*out = new(CustomizationSecurity)
		(*in).DeepCopyInto(*out)
	}
	if in.Licensing != nil {
		in, out := &in.Licensing, &out.Licensing
		*out = new(CustomizationLicensing)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CustomizationSpec.
func (in *CustomizationSpec) DeepCopy() *CustomizationSpec {
	if in == nil {
		return nil
	}
	out := new(CustomizationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CustomizationStatus) DeepCopyInto(out *CustomizationStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CustomizationStatus.
func (in *CustomizationStatus) DeepCopy() *CustomizationStatus {
	if in == nil {
		return nil
	}
	out := new(CustomizationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CustomizationSurface) DeepCopyInto(out *CustomizationSurface) {
	*out = *in
	if in.RubricScore != nil {
		in, out := &in.RubricScore, &out.RubricScore
		*out = new(int32)
		**out = **in
	}
	if in.SupportedRungs != nil {
		in, out := &in.SupportedRungs, &out.SupportedRungs
		*out = make([]CustomizationRung, len(*in))
		copy(*out, *in)
	}
	if in.Configure != nil {
		in, out := &in.Configure, &out.Configure
		*out = new(CustomizationConfigure)
		**out = **in
	}
	if in.DropIns != nil {
		in, out := &in.DropIns, &out.DropIns
		*out = make([]CustomizationDropIn, len(*in))
		copy(*out, *in)
	}
	if in.Extension != nil {
		in, out := &in.Extension, &out.Extension
		*out = new(CustomizationExtension)
		(*in).DeepCopyInto(*out)
	}
	if in.Addon != nil {
		in, out := &in.Addon, &out.Addon
		*out = new(CustomizationAddon)
		**out = **in
	}
	if in.AddonActivation != nil {
		in, out := &in.AddonActivation, &out.AddonActivation
		*out = new(CustomizationAddonActivation)
		**out = **in
	}
	if in.AddonValues != nil {
		in, out := &in.AddonValues, &out.AddonValues
		*out = make([]CustomizationAddonValues, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Publishes != nil {
		in, out := &in.Publishes, &out.Publishes
		*out = new(CustomizationPublishes)
		(*in).DeepCopyInto(*out)
	}
	if in.Repackage != nil {
		in, out := &in.Repackage, &out.Repackage
		*out = new(CustomizationRepackage)
		**out = **in
	}
	if in.Patch != nil {
		in, out := &in.Patch, &out.Patch
		*out = new(CustomizationPatch)
		**out = **in
	}
	if in.Fork != nil {
		in, out := &in.Fork, &out.Fork
		*out = new(CustomizationFork)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CustomizationSurface.
func (in *CustomizationSurface) DeepCopy() *CustomizationSurface {
	if in == nil {
		return nil
	}
	out := new(CustomizationSurface)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CustomizationTarget) DeepCopyInto(out *CustomizationTarget) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CustomizationTarget.
func (in *CustomizationTarget) DeepCopy() *CustomizationTarget {
	if in == nil {
		return nil
	}
	out := new(CustomizationTarget)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CustomizationUpstreamFirst) DeepCopyInto(out *CustomizationUpstreamFirst) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CustomizationUpstreamFirst.
func (in *CustomizationUpstreamFirst) DeepCopy() *CustomizationUpstreamFirst {
	if in == nil {
		return nil
	}
	out := new(CustomizationUpstreamFirst)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatabaseRequirement) DeepCopyInto(out *DatabaseRequirement) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatabaseRequirement.
func (in *DatabaseRequirement) DeepCopy() *DatabaseRequirement {
	if in == nil {
		return nil
	}
	out := new(DatabaseRequirement)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatabaseValueMapping) DeepCopyInto(out *DatabaseValueMapping) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatabaseValueMapping.
func (in *DatabaseValueMapping) DeepCopy() *DatabaseValueMapping {
	if in == nil {
		return nil
	}
	out := new(DatabaseValueMapping)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DerivedSecretKey) DeepCopyInto(out *DerivedSecretKey) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DerivedSecretKey.
func (in *DerivedSecretKey) DeepCopy() *DerivedSecretKey {
	if in == nil {
		return nil
	}
	out := new(DerivedSecretKey)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExportEncryption) DeepCopyInto(out *ExportEncryption) {
	*out = *in
	if in.Recipients != nil {
		in, out := &in.Recipients, &out.Recipients
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.PassphraseSecretRef != nil {
		in, out := &in.PassphraseSecretRef, &out.PassphraseSecretRef
		*out = new(SecretKeyRef)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExportEncryption.
func (in *ExportEncryption) DeepCopy() *ExportEncryption {
	if in == nil {
		return nil
	}
	out := new(ExportEncryption)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExportEncryptionStatus) DeepCopyInto(out *ExportEncryptionStatus) {
	*out = *in
	if in.Recipients != nil {
		in, out := &in.Recipients, &out.Recipients
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExportEncryptionStatus.
func (in *ExportEncryptionStatus) DeepCopy() *ExportEncryptionStatus {
	if in == nil {
		return nil
	}
	out := new(ExportEncryptionStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FilesRequirement) DeepCopyInto(out *FilesRequirement) {
	*out = *in
	if in.Capabilities != nil {
		in, out := &in.Capabilities, &out.Capabilities
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FilesRequirement.
func (in *FilesRequirement) DeepCopy() *FilesRequirement {
	if in == nil {
		return nil
	}
	out := new(FilesRequirement)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GatewayAPIBackend) DeepCopyInto(out *GatewayAPIBackend) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GatewayAPIBackend.
func (in *GatewayAPIBackend) DeepCopy() *GatewayAPIBackend {
	if in == nil {
		return nil
	}
	out := new(GatewayAPIBackend)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GatewayFrameAncestorsSpec) DeepCopyInto(out *GatewayFrameAncestorsSpec) {
	*out = *in
	if in.Origins != nil {
		in, out := &in.Origins, &out.Origins
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GatewayFrameAncestorsSpec.
func (in *GatewayFrameAncestorsSpec) DeepCopy() *GatewayFrameAncestorsSpec {
	if in == nil {
		return nil
	}
	out := new(GatewayFrameAncestorsSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IMAPRequirement) DeepCopyInto(out *IMAPRequirement) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IMAPRequirement.
func (in *IMAPRequirement) DeepCopy() *IMAPRequirement {
	if in == nil {
		return nil
	}
	out := new(IMAPRequirement)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IMAPValueMapping) DeepCopyInto(out *IMAPValueMapping) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IMAPValueMapping.
func (in *IMAPValueMapping) DeepCopy() *IMAPValueMapping {
	if in == nil {
		return nil
	}
	out := new(IMAPValueMapping)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IdentityRequirement) DeepCopyInto(out *IdentityRequirement) {
	*out = *in
	if in.OIDC != nil {
		in, out := &in.OIDC, &out.OIDC
		*out = new(OIDCClientSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.SAML != nil {
		in, out := &in.SAML, &out.SAML
		*out = new(SAMLClientSpec)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IdentityRequirement.
func (in *IdentityRequirement) DeepCopy() *IdentityRequirement {
	if in == nil {
		return nil
	}
	out := new(IdentityRequirement)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IngressSpec) DeepCopyInto(out *IngressSpec) {
	*out = *in
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IngressSpec.
func (in *IngressSpec) DeepCopy() *IngressSpec {
	if in == nil {
		return nil
	}
	out := new(IngressSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IntegrationBinding) DeepCopyInto(out *IntegrationBinding) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IntegrationBinding.
func (in *IntegrationBinding) DeepCopy() *IntegrationBinding {
	if in == nil {
		return nil
	}
	out := new(IntegrationBinding)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *IntegrationBinding) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IntegrationBindingList) DeepCopyInto(out *IntegrationBindingList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]IntegrationBinding, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IntegrationBindingList.
func (in *IntegrationBindingList) DeepCopy() *IntegrationBindingList {
	if in == nil {
		return nil
	}
	out := new(IntegrationBindingList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *IntegrationBindingList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IntegrationBindingSpec) DeepCopyInto(out *IntegrationBindingSpec) {
	*out = *in
	out.Provider = in.Provider
	out.Consumer = in.Consumer
	if in.Capabilities != nil {
		in, out := &in.Capabilities, &out.Capabilities
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Auth != nil {
		in, out := &in.Auth, &out.Auth
		*out = new(BindingAuth)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IntegrationBindingSpec.
func (in *IntegrationBindingSpec) DeepCopy() *IntegrationBindingSpec {
	if in == nil {
		return nil
	}
	out := new(IntegrationBindingSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IntegrationBindingStatus) DeepCopyInto(out *IntegrationBindingStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.SecretRef != nil {
		in, out := &in.SecretRef, &out.SecretRef
		*out = new(LocalSecretRef)
		**out = **in
	}
	if in.LastRotation != nil {
		in, out := &in.LastRotation, &out.LastRotation
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IntegrationBindingStatus.
func (in *IntegrationBindingStatus) DeepCopy() *IntegrationBindingStatus {
	if in == nil {
		return nil
	}
	out := new(IntegrationBindingStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IntegrationRef) DeepCopyInto(out *IntegrationRef) {
	*out = *in
	if in.Capabilities != nil {
		in, out := &in.Capabilities, &out.Capabilities
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IntegrationRef.
func (in *IntegrationRef) DeepCopy() *IntegrationRef {
	if in == nil {
		return nil
	}
	out := new(IntegrationRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IntegrationValueMapping) DeepCopyInto(out *IntegrationValueMapping) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IntegrationValueMapping.
func (in *IntegrationValueMapping) DeepCopy() *IntegrationValueMapping {
	if in == nil {
		return nil
	}
	out := new(IntegrationValueMapping)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KernelRequirements) DeepCopyInto(out *KernelRequirements) {
	*out = *in
	if in.Identity != nil {
		in, out := &in.Identity, &out.Identity
		*out = new(IdentityRequirement)
		(*in).DeepCopyInto(*out)
	}
	if in.Database != nil {
		in, out := &in.Database, &out.Database
		*out = new(DatabaseRequirement)
		**out = **in
	}
	if in.Storage != nil {
		in, out := &in.Storage, &out.Storage
		*out = new(StorageRequirement)
		(*in).DeepCopyInto(*out)
	}
	if in.Cache != nil {
		in, out := &in.Cache, &out.Cache
		*out = new(CacheRequirement)
		**out = **in
	}
	if in.Mail != nil {
		in, out := &in.Mail, &out.Mail
		*out = new(MailRequirement)
		(*in).DeepCopyInto(*out)
	}
	if in.MCP != nil {
		in, out := &in.MCP, &out.MCP
		*out = new(MCPRequirement)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KernelRequirements.
func (in *KernelRequirements) DeepCopy() *KernelRequirements {
	if in == nil {
		return nil
	}
	out := new(KernelRequirements)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LocalSecretRef) DeepCopyInto(out *LocalSecretRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LocalSecretRef.
func (in *LocalSecretRef) DeepCopy() *LocalSecretRef {
	if in == nil {
		return nil
	}
	out := new(LocalSecretRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MCPRequirement) DeepCopyInto(out *MCPRequirement) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MCPRequirement.
func (in *MCPRequirement) DeepCopy() *MCPRequirement {
	if in == nil {
		return nil
	}
	out := new(MCPRequirement)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MacWaiverRequest) DeepCopyInto(out *MacWaiverRequest) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MacWaiverRequest.
func (in *MacWaiverRequest) DeepCopy() *MacWaiverRequest {
	if in == nil {
		return nil
	}
	out := new(MacWaiverRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MailRequirement) DeepCopyInto(out *MailRequirement) {
	*out = *in
	if in.SMTP != nil {
		in, out := &in.SMTP, &out.SMTP
		*out = new(SMTPRequirement)
		**out = **in
	}
	if in.IMAP != nil {
		in, out := &in.IMAP, &out.IMAP
		*out = new(IMAPRequirement)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MailRequirement.
func (in *MailRequirement) DeepCopy() *MailRequirement {
	if in == nil {
		return nil
	}
	out := new(MailRequirement)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OIDCClientSpec) DeepCopyInto(out *OIDCClientSpec) {
	*out = *in
	if in.RedirectURIs != nil {
		in, out := &in.RedirectURIs, &out.RedirectURIs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.PostLogoutRedirectURIs != nil {
		in, out := &in.PostLogoutRedirectURIs, &out.PostLogoutRedirectURIs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OIDCClientSpec.
func (in *OIDCClientSpec) DeepCopy() *OIDCClientSpec {
	if in == nil {
		return nil
	}
	out := new(OIDCClientSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OIDCMapperTemplate) DeepCopyInto(out *OIDCMapperTemplate) {
	*out = *in
	if in.Config != nil {
		in, out := &in.Config, &out.Config
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OIDCMapperTemplate.
func (in *OIDCMapperTemplate) DeepCopy() *OIDCMapperTemplate {
	if in == nil {
		return nil
	}
	out := new(OIDCMapperTemplate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OIDCPackCatalog) DeepCopyInto(out *OIDCPackCatalog) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OIDCPackCatalog.
func (in *OIDCPackCatalog) DeepCopy() *OIDCPackCatalog {
	if in == nil {
		return nil
	}
	out := new(OIDCPackCatalog)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OIDCPackCatalog) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OIDCPackCatalogList) DeepCopyInto(out *OIDCPackCatalogList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]OIDCPackCatalog, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OIDCPackCatalogList.
func (in *OIDCPackCatalogList) DeepCopy() *OIDCPackCatalogList {
	if in == nil {
		return nil
	}
	out := new(OIDCPackCatalogList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OIDCPackCatalogList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OIDCPackCatalogSpec) DeepCopyInto(out *OIDCPackCatalogSpec) {
	*out = *in
	if in.MapperTemplates != nil {
		in, out := &in.MapperTemplates, &out.MapperTemplates
		*out = make(map[string]OIDCMapperTemplate, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	if in.Packs != nil {
		in, out := &in.Packs, &out.Packs
		*out = make(map[string]OIDCPackSpec, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	if in.ExtraManagedByAttributeGroups != nil {
		in, out := &in.ExtraManagedByAttributeGroups, &out.ExtraManagedByAttributeGroups
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OIDCPackCatalogSpec.
func (in *OIDCPackCatalogSpec) DeepCopy() *OIDCPackCatalogSpec {
	if in == nil {
		return nil
	}
	out := new(OIDCPackCatalogSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OIDCPackCatalogStatus) DeepCopyInto(out *OIDCPackCatalogStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OIDCPackCatalogStatus.
func (in *OIDCPackCatalogStatus) DeepCopy() *OIDCPackCatalogStatus {
	if in == nil {
		return nil
	}
	out := new(OIDCPackCatalogStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OIDCPackSpec) DeepCopyInto(out *OIDCPackSpec) {
	*out = *in
	if in.DefaultScopes != nil {
		in, out := &in.DefaultScopes, &out.DefaultScopes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Mappers != nil {
		in, out := &in.Mappers, &out.Mappers
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OIDCPackSpec.
func (in *OIDCPackSpec) DeepCopy() *OIDCPackSpec {
	if in == nil {
		return nil
	}
	out := new(OIDCPackSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OIDCValueMapping) DeepCopyInto(out *OIDCValueMapping) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OIDCValueMapping.
func (in *OIDCValueMapping) DeepCopy() *OIDCValueMapping {
	if in == nil {
		return nil
	}
	out := new(OIDCValueMapping)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PlatformSecurityPolicy) DeepCopyInto(out *PlatformSecurityPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PlatformSecurityPolicy.
func (in *PlatformSecurityPolicy) DeepCopy() *PlatformSecurityPolicy {
	if in == nil {
		return nil
	}
	out := new(PlatformSecurityPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PlatformSecurityPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PlatformSecurityPolicyList) DeepCopyInto(out *PlatformSecurityPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PlatformSecurityPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PlatformSecurityPolicyList.
func (in *PlatformSecurityPolicyList) DeepCopy() *PlatformSecurityPolicyList {
	if in == nil {
		return nil
	}
	out := new(PlatformSecurityPolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PlatformSecurityPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PlatformSecurityPolicySpec) DeepCopyInto(out *PlatformSecurityPolicySpec) {
	*out = *in
	if in.AllowedMacWaivers != nil {
		in, out := &in.AllowedMacWaivers, &out.AllowedMacWaivers
		*out = make([]AllowedMacWaiver, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PlatformSecurityPolicySpec.
func (in *PlatformSecurityPolicySpec) DeepCopy() *PlatformSecurityPolicySpec {
	if in == nil {
		return nil
	}
	out := new(PlatformSecurityPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PlatformSecurityPolicyStatus) DeepCopyInto(out *PlatformSecurityPolicyStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PlatformSecurityPolicyStatus.
func (in *PlatformSecurityPolicyStatus) DeepCopy() *PlatformSecurityPolicyStatus {
	if in == nil {
		return nil
	}
	out := new(PlatformSecurityPolicyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PortalTileSpec) DeepCopyInto(out *PortalTileSpec) {
	*out = *in
	if in.DisplayName != nil {
		in, out := &in.DisplayName, &out.DisplayName
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Tile != nil {
		in, out := &in.Tile, &out.Tile
		*out = new(TileSpec)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PortalTileSpec.
func (in *PortalTileSpec) DeepCopy() *PortalTileSpec {
	if in == nil {
		return nil
	}
	out := new(PortalTileSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PostInstallJobPVCMount) DeepCopyInto(out *PostInstallJobPVCMount) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PostInstallJobPVCMount.
func (in *PostInstallJobPVCMount) DeepCopy() *PostInstallJobPVCMount {
	if in == nil {
		return nil
	}
	out := new(PostInstallJobPVCMount)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PrivilegedRoleSpec) DeepCopyInto(out *PrivilegedRoleSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PrivilegedRoleSpec.
func (in *PrivilegedRoleSpec) DeepCopy() *PrivilegedRoleSpec {
	if in == nil {
		return nil
	}
	out := new(PrivilegedRoleSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProfileIdentity) DeepCopyInto(out *ProfileIdentity) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProfileIdentity.
func (in *ProfileIdentity) DeepCopy() *ProfileIdentity {
	if in == nil {
		return nil
	}
	out := new(ProfileIdentity)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProfileReference) DeepCopyInto(out *ProfileReference) {
	*out = *in
	if in.Identity != nil {
		in, out := &in.Identity, &out.Identity
		*out = new(ProfileIdentity)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProfileReference.
func (in *ProfileReference) DeepCopy() *ProfileReference {
	if in == nil {
		return nil
	}
	out := new(ProfileReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProvisioningEnvVar) DeepCopyInto(out *ProvisioningEnvVar) {
	*out = *in
	out.SecretKeyRef = in.SecretKeyRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProvisioningEnvVar.
func (in *ProvisioningEnvVar) DeepCopy() *ProvisioningEnvVar {
	if in == nil {
		return nil
	}
	out := new(ProvisioningEnvVar)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProvisioningJobSpec) DeepCopyInto(out *ProvisioningJobSpec) {
	*out = *in
	if in.Env != nil {
		in, out := &in.Env, &out.Env
		*out = make([]ProvisioningEnvVar, len(*in))
		copy(*out, *in)
	}
	if in.EnvFrom != nil {
		in, out := &in.EnvFrom, &out.EnvFrom
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProvisioningJobSpec.
func (in *ProvisioningJobSpec) DeepCopy() *ProvisioningJobSpec {
	if in == nil {
		return nil
	}
	out := new(ProvisioningJobSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProvisioningSecretKeyRef) DeepCopyInto(out *ProvisioningSecretKeyRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProvisioningSecretKeyRef.
func (in *ProvisioningSecretKeyRef) DeepCopy() *ProvisioningSecretKeyRef {
	if in == nil {
		return nil
	}
	out := new(ProvisioningSecretKeyRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProvisioningSpec) DeepCopyInto(out *ProvisioningSpec) {
	*out = *in
	if in.PrivilegedRole != nil {
		in, out := &in.PrivilegedRole, &out.PrivilegedRole
		*out = new(PrivilegedRoleSpec)
		**out = **in
	}
	if in.SyncJob != nil {
		in, out := &in.SyncJob, &out.SyncJob
		*out = new(ProvisioningJobSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProvisioningSpec.
func (in *ProvisioningSpec) DeepCopy() *ProvisioningSpec {
	if in == nil {
		return nil
	}
	out := new(ProvisioningSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *S3Requirement) DeepCopyInto(out *S3Requirement) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new S3Requirement.
func (in *S3Requirement) DeepCopy() *S3Requirement {
	if in == nil {
		return nil
	}
	out := new(S3Requirement)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *S3ValueMapping) DeepCopyInto(out *S3ValueMapping) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new S3ValueMapping.
func (in *S3ValueMapping) DeepCopy() *S3ValueMapping {
	if in == nil {
		return nil
	}
	out := new(S3ValueMapping)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SAMLClientSpec) DeepCopyInto(out *SAMLClientSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SAMLClientSpec.
func (in *SAMLClientSpec) DeepCopy() *SAMLClientSpec {
	if in == nil {
		return nil
	}
	out := new(SAMLClientSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SMTPRequirement) DeepCopyInto(out *SMTPRequirement) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SMTPRequirement.
func (in *SMTPRequirement) DeepCopy() *SMTPRequirement {
	if in == nil {
		return nil
	}
	out := new(SMTPRequirement)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SMTPValueMapping) DeepCopyInto(out *SMTPValueMapping) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SMTPValueMapping.
func (in *SMTPValueMapping) DeepCopy() *SMTPValueMapping {
	if in == nil {
		return nil
	}
	out := new(SMTPValueMapping)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretKeyRef) DeepCopyInto(out *SecretKeyRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretKeyRef.
func (in *SecretKeyRef) DeepCopy() *SecretKeyRef {
	if in == nil {
		return nil
	}
	out := new(SecretKeyRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecuritySpec) DeepCopyInto(out *SecuritySpec) {
	*out = *in
	if in.MacWaivers != nil {
		in, out := &in.MacWaivers, &out.MacWaivers
		*out = make([]MacWaiverRequest, len(*in))
		copy(*out, *in)
	}
	if in.Egress != nil {
		in, out := &in.Egress, &out.Egress
		*out = make([]networkingv1.NetworkPolicyEgressRule, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecuritySpec.
func (in *SecuritySpec) DeepCopy() *SecuritySpec {
	if in == nil {
		return nil
	}
	out := new(SecuritySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StorageRequirement) DeepCopyInto(out *StorageRequirement) {
	*out = *in
	if in.S3 != nil {
		in, out := &in.S3, &out.S3
		*out = new(S3Requirement)
		**out = **in
	}
	if in.Files != nil {
		in, out := &in.Files, &out.Files
		*out = new(FilesRequirement)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StorageRequirement.
func (in *StorageRequirement) DeepCopy() *StorageRequirement {
	if in == nil {
		return nil
	}
	out := new(StorageRequirement)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Tenant) DeepCopyInto(out *Tenant) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Tenant.
func (in *Tenant) DeepCopy() *Tenant {
	if in == nil {
		return nil
	}
	out := new(Tenant)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Tenant) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TenantApp) DeepCopyInto(out *TenantApp) {
	*out = *in
	if in.ProfileRef != nil {
		in, out := &in.ProfileRef, &out.ProfileRef
		*out = new(ProfileReference)
		(*in).DeepCopyInto(*out)
	}
	if in.Config != nil {
		in, out := &in.Config, &out.Config
		*out = new(TenantAppConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Addons != nil {
		in, out := &in.Addons, &out.Addons
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TenantApp.
func (in *TenantApp) DeepCopy() *TenantApp {
	if in == nil {
		return nil
	}
	out := new(TenantApp)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TenantAppConfig) DeepCopyInto(out *TenantAppConfig) {
	*out = *in
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(int32)
		**out = **in
	}
	if in.ExtraValues != nil {
		in, out := &in.ExtraValues, &out.ExtraValues
		*out = new(runtime.RawExtension)
		(*in).DeepCopyInto(*out)
	}
	if in.DropIns != nil {
		in, out := &in.DropIns, &out.DropIns
		*out = make([]TenantAppDropIn, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TenantAppConfig.
func (in *TenantAppConfig) DeepCopy() *TenantAppConfig {
	if in == nil {
		return nil
	}
	out := new(TenantAppConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TenantAppDropIn) DeepCopyInto(out *TenantAppDropIn) {
	*out = *in
	if in.Files != nil {
		in, out := &in.Files, &out.Files
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TenantAppDropIn.
func (in *TenantAppDropIn) DeepCopy() *TenantAppDropIn {
	if in == nil {
		return nil
	}
	out := new(TenantAppDropIn)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TenantExport) DeepCopyInto(out *TenantExport) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TenantExport.
func (in *TenantExport) DeepCopy() *TenantExport {
	if in == nil {
		return nil
	}
	out := new(TenantExport)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TenantExport) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TenantExportList) DeepCopyInto(out *TenantExportList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]TenantExport, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TenantExportList.
func (in *TenantExportList) DeepCopy() *TenantExportList {
	if in == nil {
		return nil
	}
	out := new(TenantExportList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TenantExportList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TenantExportSpec) DeepCopyInto(out *TenantExportSpec) {
	*out = *in
	if in.Apps != nil {
		in, out := &in.Apps, &out.Apps
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Encryption != nil {
		in, out := &in.Encryption, &out.Encryption
		*out = new(ExportEncryption)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TenantExportSpec.
func (in *TenantExportSpec) DeepCopy() *TenantExportSpec {
	if in == nil {
		return nil
	}
	out := new(TenantExportSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TenantExportStatus) DeepCopyInto(out *TenantExportStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Bundle != nil {
		in, out := &in.Bundle, &out.Bundle
		*out = new(BundleRef)
		**out = **in
	}
	if in.Apps != nil {
		in, out := &in.Apps, &out.Apps
		*out = make([]AppExportStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Quiesced != nil {
		in, out := &in.Quiesced, &out.Quiesced
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.StartedAt != nil {
		in, out := &in.StartedAt, &out.StartedAt
		*out = (*in).DeepCopy()
	}
	if in.CompletedAt != nil {
		in, out := &in.CompletedAt, &out.CompletedAt
		*out = (*in).DeepCopy()
	}
	if in.Encryption != nil {
		in, out := &in.Encryption, &out.Encryption
		*out = new(ExportEncryptionStatus)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TenantExportStatus.
func (in *TenantExportStatus) DeepCopy() *TenantExportStatus {
	if in == nil {
		return nil
	}
	out := new(TenantExportStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TenantIsolation) DeepCopyInto(out *TenantIsolation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TenantIsolation.
func (in *TenantIsolation) DeepCopy() *TenantIsolation {
	if in == nil {
		return nil
	}
	out := new(TenantIsolation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TenantList) DeepCopyInto(out *TenantList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Tenant, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TenantList.
func (in *TenantList) DeepCopy() *TenantList {
	if in == nil {
		return nil
	}
	out := new(TenantList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TenantList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TenantMail) DeepCopyInto(out *TenantMail) {
	*out = *in
	if in.QuotaPerUser != nil {
		in, out := &in.QuotaPerUser, &out.QuotaPerUser
		x := (*in).DeepCopy()
		*out = &x
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TenantMail.
func (in *TenantMail) DeepCopy() *TenantMail {
	if in == nil {
		return nil
	}
	out := new(TenantMail)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TenantMailStatus) DeepCopyInto(out *TenantMailStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TenantMailStatus.
func (in *TenantMailStatus) DeepCopy() *TenantMailStatus {
	if in == nil {
		return nil
	}
	out := new(TenantMailStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TenantQuotas) DeepCopyInto(out *TenantQuotas) {
	*out = *in
	if in.Storage != nil {
		in, out := &in.Storage, &out.Storage
		x := (*in).DeepCopy()
		*out = &x
	}
	if in.CPU != nil {
		in, out := &in.CPU, &out.CPU
		x := (*in).DeepCopy()
		*out = &x
	}
	if in.Memory != nil {
		in, out := &in.Memory, &out.Memory
		x := (*in).DeepCopy()
		*out = &x
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TenantQuotas.
func (in *TenantQuotas) DeepCopy() *TenantQuotas {
	if in == nil {
		return nil
	}
	out := new(TenantQuotas)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TenantSpec) DeepCopyInto(out *TenantSpec) {
	*out = *in
	if in.Isolation != nil {
		in, out := &in.Isolation, &out.Isolation
		*out = new(TenantIsolation)
		**out = **in
	}
	if in.Mail != nil {
		in, out := &in.Mail, &out.Mail
		*out = new(TenantMail)
		(*in).DeepCopyInto(*out)
	}
	if in.Quotas != nil {
		in, out := &in.Quotas, &out.Quotas
		*out = new(TenantQuotas)
		(*in).DeepCopyInto(*out)
	}
	if in.Apps != nil {
		in, out := &in.Apps, &out.Apps
		*out = make([]TenantApp, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TenantSpec.
func (in *TenantSpec) DeepCopy() *TenantSpec {
	if in == nil {
		return nil
	}
	out := new(TenantSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TenantStatus) DeepCopyInto(out *TenantStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ProvisionedApps != nil {
		in, out := &in.ProvisionedApps, &out.ProvisionedApps
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Mail != nil {
		in, out := &in.Mail, &out.Mail
		*out = new(TenantMailStatus)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TenantStatus.
func (in *TenantStatus) DeepCopy() *TenantStatus {
	if in == nil {
		return nil
	}
	out := new(TenantStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TileSpec) DeepCopyInto(out *TileSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TileSpec.
func (in *TileSpec) DeepCopy() *TileSpec {
	if in == nil {
		return nil
	}
	out := new(TileSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ValueMapping) DeepCopyInto(out *ValueMapping) {
	*out = *in
	if in.OIDC != nil {
		in, out := &in.OIDC, &out.OIDC
		*out = new(OIDCValueMapping)
		**out = **in
	}
	if in.Database != nil {
		in, out := &in.Database, &out.Database
		*out = new(DatabaseValueMapping)
		**out = **in
	}
	if in.S3 != nil {
		in, out := &in.S3, &out.S3
		*out = new(S3ValueMapping)
		**out = **in
	}
	if in.Cache != nil {
		in, out := &in.Cache, &out.Cache
		*out = new(CacheValueMapping)
		**out = **in
	}
	if in.SMTP != nil {
		in, out := &in.SMTP, &out.SMTP
		*out = new(SMTPValueMapping)
		**out = **in
	}
	if in.IMAP != nil {
		in, out := &in.IMAP, &out.IMAP
		*out = new(IMAPValueMapping)
		**out = **in
	}
	if in.Volumes != nil {
		in, out := &in.Volumes, &out.Volumes
		*out = new(VolumeValueMapping)
		**out = **in
	}
	if in.Integrations != nil {
		in, out := &in.Integrations, &out.Integrations
		*out = make(map[string]IntegrationValueMapping, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ValueMapping.
func (in *ValueMapping) DeepCopy() *ValueMapping {
	if in == nil {
		return nil
	}
	out := new(ValueMapping)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VolumeValueMapping) DeepCopyInto(out *VolumeValueMapping) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VolumeValueMapping.
func (in *VolumeValueMapping) DeepCopy() *VolumeValueMapping {
	if in == nil {
		return nil
	}
	out := new(VolumeValueMapping)
	in.DeepCopyInto(out)
	return out
}
