#!/usr/bin/env bash
# =============================================================================
# scripts/tools/verify-openbao-policies.sh — the OpenBao policies deny what they
# claim to deny
# =============================================================================
# Phase 7, criterion 5. The Cluster composition renders three OpenBao policies —
# eso-read, cluster-admin and tenant-admin — and the tenant-admin deny on
# gentian-os/kernel/* is the one authz rule in the system where a mistake is a
# breach rather than an annoyance. Nothing asserted it.
#
# The golden render test (crossplane/tests/unit/render/cluster-oidc-policies)
# proves the policy TEXT is emitted. That is not the same claim. A golden file
# is regenerated by `make test-unit-render-update`, so a weakened policy plus a
# regenerate leaves the suite green; and policy text that reads correctly can
# still grant something unintended, because whether a path matches is OpenBao's
# rule, not ours. This runs the policies against a real OpenBao and asserts
# capabilities.
#
# The two tests are complementary and both are needed: the golden test catches
# the text changing, this one catches the text meaning something else.
#
# The policies are read from the golden file rather than restated here. A test
# that carries its own copy of the thing under test asserts that the copy is
# self-consistent, which is the failure mode this repository keeps meeting —
# see scripts/lint/check-render-fixtures.sh for the same reasoning applied to
# the Composition copies.
#
# The tenant path is templated on alias metadata, so the test drives the real
# mechanism: a signed JWT carrying a `tenant` claim, an auth role whose
# claim_mappings turn that claim into alias metadata, and a policy that
# addresses the alias by mount accessor. That chain is the security property
# the composition's own comment states — "the path a token reaches is decided
# by the verified claim rather than by anything the caller sends" — and it is
# only observable end to end.
#
# Usage: scripts/tools/verify-openbao-policies.sh
# Requires: bao, jq, yq, openssl. Skips (exit 0) when bao is absent.
# =============================================================================

set -uo pipefail
cd "$(dirname "${BASH_SOURCE[0]}")/../.." || exit 1

RED=$'\033[0;31m'; GREEN=$'\033[0;32m'; YELLOW=$'\033[1;33m'; DIM=$'\033[2m'; NC=$'\033[0m'

GOLDEN="crossplane/tests/unit/render/cluster-oidc-policies/expected.yaml"
# The placeholder accessor in the fixture's observed OIDC backend. Swapped for
# the accessor of whichever mount this run creates, because a Vault policy
# template can only address an alias by accessor and the accessor is assigned
# at mount time.
FIXTURE_ACCESSOR="auth_oidc_1a2b3c4d"

for cmd in bao jq yq openssl; do
    if ! command -v "${cmd}" >/dev/null 2>&1; then
        echo "${YELLOW}SKIP${NC} — ${cmd} not found. This test needs ${cmd} to run a throwaway OpenBao."
        exit 0
    fi
done
[[ -f "${GOLDEN}" ]] || { echo "${RED}FAIL${NC} — ${GOLDEN} missing. Run 'make test-unit-render-update'."; exit 1; }

echo ""
echo "OpenBao policy tests — allow and deny, against a throwaway server"
echo ""

# ── a throwaway server ───────────────────────────────────────────────────────
WORKDIR="$(mktemp -d)"
BAO_PID=""
cleanup() {
    [[ -n "${BAO_PID}" ]] && kill "${BAO_PID}" 2>/dev/null
    rm -rf "${WORKDIR}"
}
trap cleanup EXIT INT TERM

# A port nobody is on. Dev mode is in-memory and unsealed, so a stale server
# from an interrupted run would answer with the wrong policies rather than
# refusing the connection — which is why this refuses to reuse a live port.
PORT=18200
while [[ ${PORT} -lt 18260 ]]; do
    (exec 3<>"/dev/tcp/127.0.0.1/${PORT}") 2>/dev/null || break
    exec 3<&- 2>/dev/null
    PORT=$((PORT + 1))
done
if [[ ${PORT} -ge 18260 ]]; then
    echo "${RED}FAIL${NC} — no free port in 18200-18259."
    exit 1
fi

export BAO_ADDR="http://127.0.0.1:${PORT}"
export BAO_TOKEN="root"
bao server -dev -dev-root-token-id=root -dev-listen-address="127.0.0.1:${PORT}" \
    > "${WORKDIR}/server.log" 2>&1 &
BAO_PID=$!

# Bounded, and paced by the cost of spawning `bao status` itself — roughly a
# hundred probes before giving up, with no sleep(1) and no fixed delay to tune.
ready=0
probes=0
while [[ ${probes} -lt 100 ]]; do
    if bao status >/dev/null 2>&1; then ready=1; break; fi
    probes=$((probes + 1))
done
if [[ ${ready} -eq 0 ]]; then
    echo "${RED}FAIL${NC} — OpenBao did not become ready on ${BAO_ADDR}."
    sed 's/^/    /' "${WORKDIR}/server.log" | tail -10
    exit 1
fi
echo "  ${DIM}dev server on ${BAO_ADDR}, KV v2 at secret/${NC}"

# ── the policies, as the composition renders them ────────────────────────────
policy_from_golden() {
    yq eval-all "select(.kind == \"Policy\" and .spec.forProvider.name == \"$1\") | .spec.forProvider.policy" \
        "${GOLDEN}" 2>/dev/null
}

bao auth enable jwt >/dev/null 2>&1
JWT_ACCESSOR="$(bao auth list -format=json 2>/dev/null | jq -r '."jwt/".accessor')"
if [[ -z "${JWT_ACCESSOR}" || "${JWT_ACCESSOR}" == "null" ]]; then
    echo "${RED}FAIL${NC} — could not enable the jwt auth method."
    exit 1
fi

loaded=0
for name in eso-read cluster-admin tenant-admin; do
    body="$(policy_from_golden "${name}")"
    if [[ -z "${body}" || "${body}" == "null" ]]; then
        echo "  ${RED}✗${NC} ${name} — not present in ${GOLDEN}"
        echo "      The composition gates cluster-admin and tenant-admin on spec.oidc.discoveryUrl"
        echo "      and an observed auth accessor. If the fixture stopped supplying either, these"
        echo "      policies vanish from the render and this test would silently cover nothing."
        exit 1
    fi
    printf '%s\n' "${body}" | sed "s/${FIXTURE_ACCESSOR}/${JWT_ACCESSOR}/g" > "${WORKDIR}/${name}.hcl"
    bao policy write "${name}" "${WORKDIR}/${name}.hcl" >/dev/null 2>&1 || {
        echo "  ${RED}✗${NC} ${name} — OpenBao rejected the policy"
        sed 's/^/      /' "${WORKDIR}/${name}.hcl"
        exit 1
    }
    loaded=$((loaded + 1))
done
echo "  ${DIM}${loaded} policies loaded from the rendered composition${NC}"

# ── a tenant-admin token whose tenant came from a verified claim ─────────────
openssl genrsa -out "${WORKDIR}/jwt.key" 2048 2>/dev/null
openssl rsa -in "${WORKDIR}/jwt.key" -pubout -out "${WORKDIR}/jwt.pub" 2>/dev/null
bao write auth/jwt/config jwt_validation_pubkeys=@"${WORKDIR}/jwt.pub" >/dev/null 2>&1
bao write auth/jwt/role/tenant-admin role_type=jwt bound_audiences=openbao \
    user_claim=sub claim_mappings=tenant=tenant token_policies=tenant-admin ttl=10m >/dev/null 2>&1

b64url() { openssl base64 -A | tr '+/' '-_' | tr -d '='; }
mint_tenant_token() {
    local tenant="$1" now hdr payload sig
    now="$(date +%s)"
    hdr="$(printf '{"alg":"RS256","typ":"JWT"}' | b64url)"
    # nbf and iat backdated: OpenBao rejects a token whose nbf has not arrived,
    # and a test that fails on sub-second clock skew is a flaky test.
    payload="$(printf '{"sub":"admin@%s","aud":"openbao","tenant":"%s","iat":%d,"nbf":%d,"exp":%d}' \
        "${tenant}" "${tenant}" "$((now - 60))" "$((now - 60))" "$((now + 600))" | b64url)"
    sig="$(printf '%s.%s' "${hdr}" "${payload}" | openssl dgst -sha256 -sign "${WORKDIR}/jwt.key" -binary | b64url)"
    bao write -format=json auth/jwt/login role=tenant-admin jwt="${hdr}.${payload}.${sig}" 2>/dev/null |
        jq -r '.auth.client_token // empty'
}

TENANT_TOKEN="$(mint_tenant_token acme)"
if [[ -z "${TENANT_TOKEN}" ]]; then
    echo "${RED}FAIL${NC} — JWT login produced no token; the claim-mapping chain is untestable."
    exit 1
fi

CLUSTER_TOKEN="$(bao token create -policy=cluster-admin -ttl=10m -format=json 2>/dev/null | jq -r '.auth.client_token')"
ESO_TOKEN="$(bao token create -policy=eso-read -ttl=10m -format=json 2>/dev/null | jq -r '.auth.client_token')"

# ── assertions ───────────────────────────────────────────────────────────────
pass=0; fail=0

# expect <token> <label> <path> <expected-capabilities, comma-separated or "deny">
expect() {
    local token="$1" label="$2" path="$3" want="$4" got norm_got norm_want
    got="$(BAO_TOKEN="${token}" bao token capabilities "${path}" 2>&1)"
    # `bao token capabilities` prints capabilities in an unspecified order, so
    # compare as sets. A root-like list would contain "root"; treat it as a
    # mismatch rather than a pass, since it would mean the token is not the one
    # under test.
    norm_got="$(printf '%s' "${got}" | tr ',' '\n' | tr -d ' ' | sort | tr '\n' ',')"
    norm_want="$(printf '%s' "${want}" | tr ',' '\n' | tr -d ' ' | sort | tr '\n' ',')"
    if [[ "${norm_got}" == "${norm_want}" ]]; then
        printf '    %s✓%s %-58s %s\n' "${GREEN}" "${NC}" "${label}" "${DIM}${want}${NC}"
        pass=$((pass + 1))
    else
        printf '    %s✗%s %-58s want [%s] got [%s]\n' "${RED}" "${NC}" "${label}" "${want}" "${got}"
        fail=$((fail + 1))
    fi
}

echo ""
echo "  tenant-admin ${DIM}(tenant=acme, from the JWT claim)${NC}"
expect "${TENANT_TOKEN}" "DENIED kernel data — a breach if this ever passes" \
    "secret/data/gentian-os/kernel/dns/cloudflare" "deny"
expect "${TENANT_TOKEN}" "DENIED kernel metadata — path names leak too" \
    "secret/metadata/gentian-os/kernel/dns/cloudflare" "deny"
expect "${TENANT_TOKEN}" "DENIED another tenant's data" \
    "secret/data/gentian-os/tenants/other/repositories/x" "deny"
expect "${TENANT_TOKEN}" "DENIED another tenant's metadata" \
    "secret/metadata/gentian-os/tenants/other/repositories/x" "deny"
expect "${TENANT_TOKEN}" "allowed own tenant data" \
    "secret/data/gentian-os/tenants/acme/repositories/x" "create,read,update"
expect "${TENANT_TOKEN}" "allowed own tenant metadata (records who set a value)" \
    "secret/metadata/gentian-os/tenants/acme/repositories/x" "create,list,read,update"

# The claim decides the path, not the caller. A second identity asking for a
# different tenant must land somewhere else entirely — this is what makes the
# isolation above a property of the token rather than of the path string.
OTHER_TOKEN="$(mint_tenant_token globex)"
echo ""
echo "  tenant-admin ${DIM}(a second identity, tenant=globex)${NC}"
expect "${OTHER_TOKEN}" "DENIED the first tenant's data" \
    "secret/data/gentian-os/tenants/acme/repositories/x" "deny"
expect "${OTHER_TOKEN}" "allowed its own tenant's data" \
    "secret/data/gentian-os/tenants/globex/repositories/x" "create,read,update"

echo ""
echo "  cluster-admin"
expect "${CLUSTER_TOKEN}" "allowed kernel data" \
    "secret/data/gentian-os/kernel/dns/cloudflare" "create,read,update"
expect "${CLUSTER_TOKEN}" "allowed kernel metadata" \
    "secret/metadata/gentian-os/kernel/dns/cloudflare" "list,read"
expect "${CLUSTER_TOKEN}" "DENIED a tenant's data — cluster-admin is not a superuser here" \
    "secret/data/gentian-os/tenants/acme/repositories/x" "deny"
expect "${CLUSTER_TOKEN}" "DENIED paths outside gentian-os" \
    "secret/data/somewhere/else" "deny"

echo ""
echo "  eso-read ${DIM}(the only identity ESO holds)${NC}"
expect "${ESO_TOKEN}" "allowed reading kernel data" \
    "secret/data/gentian-os/kernel/dns/cloudflare" "read"
expect "${ESO_TOKEN}" "read-only — no write on kernel data" \
    "secret/metadata/gentian-os/kernel/dns/cloudflare" "list"
expect "${ESO_TOKEN}" "allowed reading a tenant's app credentials" \
    "secret/data/gentian-os/tenants/acme/apps/some-app" "read"
expect "${ESO_TOKEN}" "allowed reading a tenant's repository credentials" \
    "secret/data/gentian-os/tenants/acme/repositories/x" "read"
expect "${ESO_TOKEN}" "DENIED paths outside gentian-os" \
    "secret/data/somewhere/else" "deny"

# ── operator-write ───────────────────────────────────────────────────────────
# Not from the golden render: this one is a kernel service manifest rather than
# something the composition emits. It is here because it failed in the direction
# the tests above do not look for — it DENIED what it meant to allow.
#
# The policy read as though it granted the tenant OIDC mounts. It used
# "sys/auth/oidc-+", and OpenBao's + matches one whole path segment, so a literal
# prefix with + glued to it matches nothing: every tenant reconcile stopped at
# "configure auth mount oidc-<tenant>: HTTP 403" while the policy looked right.
#
# So these assert the allow side as well as the deny side. A policy that grants
# nothing is as broken as one that grants everything; it just fails somewhere
# less alarming.
OPERATOR_POLICY_FILE="kernel/services/openbao-config/manifests/templates/policy-operator-write.yaml"
if [[ -f "${OPERATOR_POLICY_FILE}" ]]; then
    yq eval 'select(.spec.forProvider.name == "operator-write") | .spec.forProvider.policy' \
        "${OPERATOR_POLICY_FILE}" > "${WORKDIR}/operator-write.hcl" 2>/dev/null
    if [[ -s "${WORKDIR}/operator-write.hcl" ]]; then
        bao policy write operator-write "${WORKDIR}/operator-write.hcl" >/dev/null 2>&1
        OPERATOR_TOKEN="$(bao token create -policy=operator-write -field=token 2>/dev/null)"

        echo ""
        echo "  operator-write ${DIM}(the operator's own identity)${NC}"
        expect "${OPERATOR_TOKEN}" "allowed creating a tenant OIDC mount" \
            "sys/auth/oidc-acme" "create,read,update,delete,sudo"
        expect "${OPERATOR_TOKEN}" "allowed configuring that mount" \
            "auth/oidc-acme/config" "create,read,update,delete,list"
        expect "${OPERATOR_TOKEN}" "allowed managing its roles" \
            "auth/oidc-acme/role/tenant" "create,read,update,delete,list"
        expect "${OPERATOR_TOKEN}" "DENIED the Kubernetes auth mount it authenticates with" \
            "auth/kubernetes/config" "deny"
        expect "${OPERATOR_TOKEN}" "DENIED enabling a non-OIDC auth backend" \
            "sys/auth/kubernetes" "deny"
        expect "${OPERATOR_TOKEN}" "DENIED the kernel's own OIDC mount" \
            "auth/oidc/config" "deny"
        expect "${OPERATOR_TOKEN}" "allowed its own secret tree" \
            "secret/data/gentian-os/kernel/dns/cloudflare" "create,read,update,delete"
    else
        echo "    ${YELLOW}SKIP${NC} — could not read operator-write from ${OPERATOR_POLICY_FILE}"
    fi
else
    echo "    ${YELLOW}SKIP${NC} — ${OPERATOR_POLICY_FILE} not found"
fi

echo ""
if [[ ${fail} -gt 0 ]]; then
    echo "${RED}${fail} assertion(s) failed, ${pass} passed.${NC}"
    echo "A tenant-admin failure here is a tenant reaching cluster credentials. Treat it as a breach,"
    echo "not a broken test: check crossplane/compositions/cluster-default.yaml before the fixture."
    exit 1
fi
echo "${GREEN}${pass} assertions passed.${NC} The deny on gentian-os/kernel/* holds, and a tenant's"
echo "reach is decided by the verified claim rather than by anything the caller sends."
