apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "gentian-app.fullname" . }}-web
  labels:
    app.kubernetes.io/name: {{ include "gentian-app.name" . }}-web
spec:
  replicas: {{ .Values.web.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "gentian-app.name" . }}-web
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "gentian-app.name" . }}-web
    spec:
      containers:
        - name: web
          image: "{{ .Values.web.image.repository }}:{{ .Values.web.image.tag }}"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
