#!/usr/bin/env python3
"""Render the Keycloak login theme into the ConfigMap Argo CD applies.

The theme is authored as real files under kernel/services/keycloak-idp/theme/ so
the FreeMarker templates and CSS can be edited, diffed and linted like source.
Keycloak wants them on disk and the delivery mechanism is a ConfigMap volume, so
they have to appear in YAML too. Maintaining both by hand would be two copies of
one thing, which this repository has been bitten by more than once — a validator
reading a renamed field, a CRD citing a deleted document. So the YAML is
generated and `make verify-gen` fails when it drifts.

One flat ConfigMap, expanded into Keycloak's nested layout by an init container.

A ConfigMap key cannot contain "/", so the tree is encoded as "__" and restored at
startup. The alternatives were worse. Per-file subPath mounts, or a per-file
`items` list, both mean every new template also needs a matching entry in the
Helm values — the same duplication one level down. A ConfigMap per directory does
not work at all: login/resources/css would have to mount *inside* the read-only
login volume, which contains no such directory to mount onto.

With the init container, adding a template changes only this file's output.
"""

from __future__ import annotations

import pathlib
import sys

REPO = pathlib.Path(__file__).resolve().parent.parent
THEME = REPO / "kernel/services/keycloak-idp/theme"
# One output per environment, not one shared file: the kernel ApplicationSet
# syncs kernel/services/<app>/manifests/<env>, so anything at the manifests/ root
# is never applied. The copies are byte-identical and both generated, so there is
# nothing to keep in sync by hand.
ENVS = ("dev", "prod")
OUTS = [
    REPO / f"kernel/services/keycloak-idp/manifests/{env}/theme-configmap.yaml"
    for env in ENVS
]

HEADER = """# GENERATED by scripts/gen-keycloak-theme-configmap.py — do not edit.
#
# Source of truth: kernel/services/keycloak-idp/theme/
# Regenerate with: make gen-theme     (verified by: make verify-gen)
#
# The Gentian login theme. Keys are theme-relative paths with "/" replaced by
# "__", because a ConfigMap key may not contain a slash; the init container in
# the keycloakx values expands them back into /opt/keycloak/themes/gentian.
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-idp-theme
  namespace: platform-kernel
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
data:
"""


def render() -> tuple[str, int]:
    files = sorted(p for p in THEME.rglob("*") if p.is_file())
    if not files:
        sys.exit(f"no theme files under {THEME}")

    out = [HEADER]
    for path in files:
        rel = str(path.relative_to(THEME))
        if "__" in rel:
            sys.exit(f"{rel}: a literal '__' in a theme path is ambiguous once encoded")
        text = path.read_text()
        if "\r" in text:
            sys.exit(f"{rel}: CRLF line endings would reach Keycloak verbatim")
        # "|-" rather than "|" so a missing trailing newline in a source file
        # cannot silently change the rendered bytes.
        out.append(f"  {rel.replace('/', '__')}: |-\n")
        for line in text.rstrip("\n").split("\n"):
            out.append(f"    {line}\n" if line else "\n")
    return "".join(out), len(files)


def main() -> int:
    rendered, count = render()
    if "--check" in sys.argv:
        stale = [o for o in OUTS if (o.read_text() if o.exists() else "") != rendered]
        if stale:
            for o in stale:
                print(f"{o.relative_to(REPO)} is out of date — run 'make gen-theme'")
            return 1
        print(f"theme ConfigMaps are up to date ({count} theme file(s))")
        return 0
    for o in OUTS:
        o.write_text(rendered)
        print(f"wrote {o.relative_to(REPO)} ({count} theme file(s))")
    return 0


if __name__ == "__main__":
    sys.exit(main())
