#!/usr/bin/env python3
# =============================================================================
# scripts/lint/lint-rbac-coverage.py — can the operator read what it reads?
# =============================================================================
# The operator reads resources it does not own. Crossplane composes a Keycloak
# Client, a cert-manager Certificate, a CNPG Database; the operator waits on
# them. Each of those reads needs a rule in the ClusterRole, and nothing checked
# that it had one.
#
# Nothing could. envtest does not enforce RBAC — the API server it starts has
# authorization disabled — so the whole controller suite passes with a
# ServiceAccount that would be refused on a real cluster. On 2026-08-21 the mail
# reconcile began waiting on the composed gentian-dovecot Client. Every test
# passed, including the ones written for that wait. The deploy reported:
#
#   clients.openidclient.keycloak.crossplane.io "corp-dovecot-oidc-client" is
#   forbidden: User "system:serviceaccount:gentian-system:gentian-os" cannot get
#   resource "clients" in API group "openidclient.keycloak.crossplane.io"
#
# and every tenant reconcile failed until the marker was added.
#
# This is the direction the codebase is moving in, which is why it wants a lint
# rather than a memo: replacing an imperative Job with a wait on the object
# Crossplane owns turns a write the operator already had rights to into a read
# it may not. Each such step arms the same trap.
#
# WHAT IT CHECKS
#
# Every `schema.GroupVersionKind{...}` the operator constructs must have a
# matching apiGroup/resource rule in the generated ClusterRole. Typed clients
# (`&batchv1.Job{}`) are not checked: their kinds come from the scheme, resolving
# them means resolving Go types, and they are not where this goes wrong.
# Unstructured GVKs are, precisely because they name a CRD the operator does not
# own and are written out by hand.
#
# WHAT IT DOES NOT CHECK
#
# Verbs. A rule granting `get` where the code Lists would still pass here. That
# needs to know which call each GVK reaches, which this deliberately does not
# attempt — a missing rule is the failure that has actually happened, twice, and
# a check that reports it is worth more than one that reports nothing until it
# can report everything.
#
# Usage:
#   python3 scripts/lint/lint-rbac-coverage.py
# =============================================================================
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parents[2]
CLUSTERROLE = ROOT / "charts/gentian-os/templates/clusterrole.yaml"
SCAN_ROOT = ROOT / "internal"

RED = "\033[0;31m"
YELLOW = "\033[0;33m"
GREEN = "\033[0;32m"
DIM = "\033[2m"
NC = "\033[0m"


def plural(kind: str) -> str:
    """Kind to resource, the way the API server pluralises it.

    Not a general English pluraliser and does not need to be: Kubernetes kinds
    are CamelCase nouns, and the API machinery lowercases and applies exactly
    these rules. Policy -> policies, Class -> classes, Gateway -> gateways.
    """
    k = kind.lower()
    if k.endswith("y") and not k.endswith(("ay", "ey", "iy", "oy", "uy")):
        return k[:-1] + "ies"
    if k.endswith(("s", "x", "z", "ch", "sh")):
        return k + "es"
    return k + "s"


def load_clusterrole():
    """Return {(apiGroup, resource)} plus the wildcard groups, from the chart.

    The file is a Helm template. Rather than render it, the templating is
    stripped: the rules themselves are generated by gen-clusterrole.py and carry
    no conditionals, so what remains is plain YAML.
    """
    try:
        import yaml
    except ImportError:
        print(f"{YELLOW}SKIP{NC} — PyYAML not installed.")
        sys.exit(0)

    raw = CLUSTERROLE.read_text()
    doc = yaml.safe_load(re.sub(r"\{\{-?.*?-?\}\}", "", raw, flags=re.S))
    pairs, wildcard_groups = set(), set()
    for rule in doc.get("rules", []) or []:
        groups = rule.get("apiGroups", []) or []
        resources = rule.get("resources", []) or []
        for g in groups:
            if "*" in resources:
                wildcard_groups.add(g)
            for r in resources:
                pairs.add((g, r.split("/", 1)[0]))
    return pairs, wildcard_groups


GVK_LITERAL = re.compile(r"schema\.GroupVersionKind\{(.*?)\}", re.S)
FIELD_STR = r'{}\s*:\s*"([^"]*)"'
# `Group: someGVK.Group` — a GVK defined from another one, which is common
# enough to resolve rather than report.
FIELD_REF = r"{}\s*:\s*([A-Za-z_][A-Za-z0-9_]*)\.Group"
VAR_GVK = re.compile(
    r"(?:var\s+)?([A-Za-z_][A-Za-z0-9_]*)\s*=\s*schema\.GroupVersionKind\{(.*?)\}", re.S
)


def scan_sources():
    """Yield (group, kind, location, unresolved_expr) for every GVK literal."""
    # Package-level GVK vars first, so `Group: helmReleaseGVK.Group` resolves.
    known = {}
    files = [
        p
        for p in sorted(SCAN_ROOT.rglob("*.go"))
        if not p.name.endswith("_test.go")
    ]
    for p in files:
        for m in VAR_GVK.finditer(p.read_text()):
            g = re.search(FIELD_STR.format("Group"), m.group(2))
            if g:
                known[m.group(1)] = g.group(1)

    for p in files:
        text = p.read_text()
        rel = p.relative_to(ROOT)
        for m in GVK_LITERAL.finditer(text):
            body = m.group(1)
            kind_m = re.search(FIELD_STR.format("Kind"), body)
            if not kind_m:
                continue
            kind = kind_m.group(1)
            line = text.count("\n", 0, m.start()) + 1
            loc = f"{rel}:{line}"

            gm = re.search(FIELD_STR.format("Group"), body)
            if gm:
                yield gm.group(1), kind, loc, None
                continue
            rm = re.search(FIELD_REF.format("Group"), body)
            if rm and rm.group(1) in known:
                yield known[rm.group(1)], kind, loc, None
                continue
            yield None, kind, loc, (rm.group(1) + ".Group" if rm else "a constant")


def main() -> int:
    if not CLUSTERROLE.exists():
        print(f"{YELLOW}SKIP{NC} — {CLUSTERROLE.relative_to(ROOT)} not found.")
        return 0

    pairs, wildcard_groups = load_clusterrole()
    missing, unresolved, checked = [], [], set()

    for group, kind, loc, unres in scan_sources():
        if unres is not None:
            unresolved.append((kind, loc, unres))
            continue
        # A List kind is served by the same resource as its item.
        base = kind[:-4] if kind.endswith("List") and len(kind) > 4 else kind
        resource = plural(base)
        key = (group, resource)
        if key in checked:
            continue
        checked.add(key)
        if group in wildcard_groups or key in pairs:
            continue
        missing.append((group, resource, kind, loc))

    print("")
    print("RBAC coverage — every GroupVersionKind the operator builds")
    print(f"{DIM}────────────────────────────────────────────────────────────{NC}")

    for kind, loc, expr in sorted(unresolved):
        print(f"  {YELLOW}WARN{NC}  {kind}: group comes from {expr}, not a literal.")
        print(f"        {DIM}{loc} — not checked.{NC}")

    for group, resource, kind, loc in sorted(missing):
        print(f"  {RED}ERROR{NC} {group}/{resource} is read but the ClusterRole does not grant it.")
        print(f"        {DIM}{kind} at {loc}{NC}")

    print(f"{DIM}────────────────────────────────────────────────────────────{NC}")
    if missing:
        print(f"{RED}{len(missing)} resource(s) the operator reads without permission.{NC}")
        print(f"{DIM}Add a +kubebuilder:rbac marker under ./internal/... and run 'make manifests'.{NC}")
        print(f"{DIM}envtest will not catch this: it does not enforce RBAC.{NC}")
        return 1
    suffix = f", {len(unresolved)} not checked" if unresolved else ""
    print(f"{GREEN}Every GroupVersionKind the operator builds is granted{NC} "
          f"({len(checked)} group/resource pairs{suffix}).")
    return 0


if __name__ == "__main__":
    sys.exit(main())
