apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: postgresql-credentials
  namespace: gentian-infra-dev
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: openbao
    kind: ClusterSecretStore
  target:
    name: postgresql-credentials
    creationPolicy: Owner
  data:
    - secretKey: postgres-password
      remoteRef:
        key: gentian-os/kernel/database/postgresql
        property: postgres_password
    - secretKey: keycloak-password
      remoteRef:
        key: gentian-os/kernel/database/postgresql
        property: keycloak_user_password
    - secretKey: keycloak-extensions-password
      remoteRef:
        key: gentian-os/kernel/database/postgresql
        property: keycloak_extensions_user_password
    - secretKey: selfservice-password
      remoteRef:
        key: gentian-os/kernel/database/postgresql
        property: selfservice_user_password
    - secretKey: authsession-password
      remoteRef:
        key: gentian-os/kernel/database/postgresql
        property: authsession_user_password
    - secretKey: guardian-password
      remoteRef:
        key: gentian-os/kernel/database/postgresql
        property: guardianmanagementapi_user_password
    - secretKey: notifications-password
      remoteRef:
        key: gentian-os/kernel/database/postgresql
        property: notificationsapi_user_password
