/*
Copyright 2026 Gentian Organization.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package gitops

// Generated by scripts/gen/gen-cluster-setting-defaults.py from
// crossplane/xrds/cluster.yaml. Do not edit: the XRD is where a default is
// decided, and a second copy maintained here would agree with it only until
// one of them moved.
//
// A setting absent from this map has no default in the schema, which is a
// real answer: unset means unset, and the console says so rather than showing
// a value nothing will apply.
var clusterSettingDefaults = map[string]string{
	"certificates.acmeEnv": "production",
	"certificates.issuerMode": "acme-dns01",
	"llm.enabled": "false",
	"llm.gpuAcceleration": "false",
	"mail.serviceMode": "external",
	"mail.port": "587",
	"mail.starttls": "true",
	"mail.ssl": "false",
	"tenancyMode": "multi",
	"platformRoles.admin": "gentian:platform:admin",
	"tenantDefaults.limitRange.defaultCpu": "500m",
	"tenantDefaults.limitRange.defaultMemory": "512Mi",
	"tenantDefaults.limitRange.defaultRequestCpu": "100m",
	"tenantDefaults.limitRange.defaultRequestMemory": "128Mi",
}
