/*
Copyright The Gentian OS Authors.

This Source Code Form is subject to the terms of the Mozilla Public
License, v. 2.0. If a copy of the MPL was not distributed with this
file, You can obtain one at https://mozilla.org/MPL/2.0/.

SPDX-License-Identifier: MPL-2.0
*/

package gitops

// Generated by scripts/gen/gen-cluster-setting-defaults.py from
// crossplane/xrds/cluster.yaml. Do not edit: the XRD is where a default is
// decided, and a second copy maintained here would agree with it only until
// one of them moved.
//
// A setting absent from this map has no default in the schema, which is a
// real answer: unset means unset, and the console says so rather than showing
// a value nothing will apply.
var clusterSettingDefaults = map[string]string{
	"certificates.acmeEnv":                           "production",
	"certificates.issuerMode":                        "acme-dns01",
	"llm.enabled":                                    "false",
	"llm.gpuAcceleration":                            "false",
	"mail.serviceMode":                               "external",
	"mail.port":                                      "587",
	"mail.starttls":                                  "true",
	"mail.ssl":                                       "false",
	"tenancyMode":                                    "multi",
	"platformRoles.admin":                            "gentian:platform:admin",
	"tenantDefaults.limitRange.defaultCpu":           "500m",
	"tenantDefaults.limitRange.defaultMemory":        "512Mi",
	"tenantDefaults.limitRange.defaultRequestCpu":    "100m",
	"tenantDefaults.limitRange.defaultRequestMemory": "128Mi",
}
