{{/*
SPDX-FileCopyrightText: 2023 Bundesministerium des Innern und für Heimat, PG ZenDiS "Projektgruppe für Aufbau ZenDiS"
SPDX-License-Identifier: Apache-2.0
*/}}
{{- if .Values.job.enabled }}
{{- $connection := printf "--host=%s --user=%s --password=%s" (include "common.names.fullname" .) "root" "${MARIADB_ROOT_PASSWORD}" }}
---
apiVersion: "v1"
kind: "Secret"
metadata:
  name: {{ printf "%s-job" (include "common.names.fullname" . ) | quote }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" . ) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" . ) | nindent 4 }}
  {{- end }}
stringData:
  init-wait.sh: |
    RETRIES={{ .Values.job.retries }}
    until mariadb-admin status {{ $connection }} > /dev/null 2>&1 || [ $RETRIES -eq 0 ]; do
      echo "Waiting {{ .Values.job.wait }}s for mariadb server, $((RETRIES--)) remaining attempts..."
      sleep {{ .Values.job.wait }}
    done
    if [ ${RETRIES} -eq "0" ]; then
      echo "Maximum wait attempts exceeded, aborting".
      exit 1;
    fi
  init-user-data.sql: |
    {{- range .Values.job.users }}
    CREATE USER IF NOT EXISTS {{ tpl .username $ | quote }}@"%" IDENTIFIED BY {{ tpl .password $ | quote }};
    ALTER USER {{ tpl .username $ | quote }}@"%" WITH MAX_USER_CONNECTIONS {{ tpl ( .connectionLimit | toString ) $ }};
    ALTER USER {{ tpl .username $ | quote }}@"%" IDENTIFIED BY {{ tpl .password $ | quote }};
    {{- end }}
  init-user.sh: |
    mariadb {{ $connection }}
  init-db.sh: |
    {{- range .Values.job.databases }}
    mariadb {{ $connection }} -e "CREATE DATABASE IF NOT EXISTS {{ tpl .name $ }};"
    mariadb {{ $connection }} -e 'GRANT ALL PRIVILEGES ON {{ tpl .name $ }}.* TO {{ tpl .user $ | quote }}@"%";'
    mariadb {{ $connection }} -e "FLUSH PRIVILEGES;"
    {{- end }}
...
{{- end }}
