# SPDX-FileCopyrightText: 2023 Bundesministerium des Innern und für Heimat, PG ZenDiS "Projektgruppe für Aufbau ZenDiS"
# SPDX-License-Identifier: Apache-2.0
---
# The global properties are used to configure multiple charts at once.
global:
  # -- Container registry address.
  registry: "docker.io"

  # -- Credentials to fetch images from private registry.
  # Ref: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
  #
  # imagePullSecrets:
  #   - "docker-registry"
  #
  imagePullSecrets: []

# -- Affinity for pod assignment.
# Ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#affinity-and-anti-affinity
# Note: podAffinityPreset, podAntiAffinityPreset, and nodeAffinityPreset will be ignored when it's set.
affinity: {}

# Helm release cleanup setting.
cleanup:
  # -- Keep Pods/Job logs after successful run.
  deletePodsOnSuccess: true
  # -- When deletePodsOnSuccess is enabled, the pod will be deleted after configured seconds.
  deletePodsOnSuccessTimeout: 3600

# -- Additional custom annotations to add to all deployed objects.
commonAnnotations: {}

# -- Additional custom labels to add to all deployed objects.
commonLabels: {}

# Security Context.
# Ref: https://kubernetes.io/docs/tasks/configure-pod-container/security-context/
containerSecurityContext:
  # -- Enable container privileged escalation.
  allowPrivilegeEscalation: false

  # -- Security capabilities for container.
  capabilities:
    drop:
      - "ALL"

  # -- Enable security context.
  enabled: true

  # -- Process user id.
  runAsUser: 1001

  # -- Process group id.
  runAsGroup: 1001

  # Set Seccomp profile.
  seccompProfile:
    # -- Disallow custom Seccomp profile by setting it to RuntimeDefault.
    type: "RuntimeDefault"

  # -- Mounts the container's root filesystem as read-only.
  readOnlyRootFilesystem: true

  # -- Run container as user.
  runAsNonRoot: true


# -- Array with extra environment variables to add to containers.
#
# extraEnvVars:
#   - name: FOO
#     value: "bar"
#
extraEnvVars: []

# -- Name of existing ConfigMap containing extra env vars.
extraEnvVarsCM: ""

# -- Name of existing Secret containing extra env vars.
extraEnvVarsSecret: ""

# -- Additional pod specs.
extraPodSpec: {}

# -- Optionally specify extra list of additional volumes.
extraVolumes: []

# -- Optionally specify extra list of additional volumeMounts.
extraVolumeMounts: []

# -- Provide a name to substitute for the full names of resources.
fullnameOverride: ""

# -- Specify if host IPC should be enabled for pod.
hostIPC: false

# -- Specify if host network should be enabled for pod.
hostNetwork: false

# Define image.
image:
  # -- Container registry address. This setting has higher precedence than global.registry.
  registry: ""

  # -- Container repository string.
  repository: "postgres"

  # -- Define an ImagePullPolicy.
  #
  # Ref.: https://kubernetes.io/docs/concepts/containers/images/#image-pull-policy
  #
  # "IfNotPresent" => The image is pulled only if it is not already present locally.
  # "Always" => Every time the kubelet launches a container, the kubelet queries the container image registry to
  #             resolve the name to an image digest. If the kubelet has a container image with that exact digest cached
  #             locally, the kubelet uses its cached image; otherwise, the kubelet pulls the image with the resolved
  #             digest, and uses that image to launch the container.
  # "Never" => The kubelet does not try fetching the image. If the image is somehow already present locally, the
  #            kubelet attempts to start the container; otherwise, startup fails.
  imagePullPolicy: "IfNotPresent"

  # -- Define image tag.
  tag: "15-alpine"

# -- Credentials to fetch images from private registry.
# Ref: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
#
# imagePullSecrets:
#   - "docker-registry"
#
imagePullSecrets: []

# This job bootstrap the database server with databases and users.
job:
  # -- Enable database bootstrapping.
  enabled: true

  # -- Job image.
  image:
    # -- Container registry address. This setting has higher precedence than global.registry.
    registry: ""

    # -- Container repository string.
    repository: "governmentpaas/psql"

    # -- Define an ImagePullPolicy.
    #
    # Ref.: https://kubernetes.io/docs/concepts/containers/images/#image-pull-policy
    #
    # "IfNotPresent" => The image is pulled only if it is not already present locally.
    # "Always" => Every time the kubelet launches a container, the kubelet queries the container image registry to
    #             resolve the name to an image digest. If the kubelet has a container image with that exact digest cached
    #             locally, the kubelet uses its cached image; otherwise, the kubelet pulls the image with the resolved
    #             digest, and uses that image to launch the container.
    # "Never" => The kubelet does not try fetching the image. If the image is somehow already present locally, the
    #            kubelet attempts to start the container; otherwise, startup fails.
    #
    imagePullPolicy: "IfNotPresent"

    # -- Define image tag.
    tag: "latest"

  # -- Amount of retries while waiting for postgresql server is available.
  retries: 60

  # -- Time to wait in each wait in each iteration until postgresql server is available.
  wait: 5

  # -- Bootstrap users into postgresql server. When a user already exists its password and user specific
  # connectionLimit are updated.
  #
  # users:
  #   - username: "name_of_user"
  #     password: "RandomPassword0#"
  #     connectionLimit: 10
  users: []

  # -- Bootstrap databases into postgresql server. When databases already exists, they will stay untouched.
  #
  # databases:
  #  - name: "name_of_database"
  #    user: "existing_user_which_will_get_grant"
  #    additionalParams: "" # Optional
  databases: []

# -- Lifecycle to automate configuration before or after startup.
lifecycleHooks: {}

#  Configure extra options for containers probes.
livenessProbe:
  # -- Enables kubernetes LivenessProbe.
  enabled: true
  # -- Delay after container start until LivenessProbe is executed.
  initialDelaySeconds: 15
  # -- Time between probe executions.
  periodSeconds: 10
  # -- Timeout for command return.
  timeoutSeconds: 5
  # -- Number of failed executions until container is terminated.
  failureThreshold: 6
  # -- Number of successful executions after failed ones until container is marked healthy.
  successThreshold: 1


# -- String to partially override release name.
nameOverride: ""

# -- Node labels for pod assignment.
# Ref: https://kubernetes.io/docs/user-guide/node-selection/
nodeSelector: {}

# Persistence configuration.
persistence:
  # -- The volume access modes, some of "ReadWriteOnce", "ReadOnlyMany", "ReadWriteMany", "ReadWriteOncePod".
  #
  # "ReadWriteOnce" => The volume can be mounted as read-write by a single node. ReadWriteOnce access mode still can
  #                    allow multiple pods to access the volume when the pods are running on the same node.
  # "ReadOnlyMany" => The volume can be mounted as read-only by many nodes.
  # "ReadWriteMany" => The volume can be mounted as read-write by many nodes.
  # "ReadWriteOncePod" => The volume can be mounted as read-write by a single Pod. Use ReadWriteOncePod access mode if
  #                       you want to ensure that only one pod across whole cluster can read that PVC or write to it.
  #
  accessModes:
    - "ReadWriteOnce"

  # -- Annotations for the PVC.
  annotations: {}

  # -- Custom PVC data source.
  dataSource: {}

  # -- Enable data persistence (true) or use temporary storage (false).
  enabled: true

  # -- Use an already existing claim.
  existingClaim: ""

  # -- Labels for the PVC.
  labels: {}

  # -- The volume size with unit.
  size: "8Gi"

  # -- The (storage) class of PV.
  storageClass: ""

  # -- Selector to match an existing Persistent Volume (this value is evaluated as a template)
  #
  # selector:
  #   matchLabels:
  #     app: my-app
  #
  selector: {}

# -- Pod Annotations.
# Ref: https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/
podAnnotations: {}

# -- Pod Labels.
# Ref: https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/
podLabels: {}

# Pod Security Context.
# Ref: https://kubernetes.io/docs/tasks/configure-pod-container/security-context/
podSecurityContext:
  # -- Enable security context.
  enabled: true

  # -- If specified, all processes of the container are also part of the supplementary group.
  fsGroup: 1001

  # -- Change ownership and permission of the volume before being exposed inside a Pod.
  fsGroupChangePolicy: "OnRootMismatch"

# PostgreSQL configuration.
postgres:
  # -- PostgreSQL additional configuration to be injected as ConfigMap.
  configuration: ""

  # -- Database user.
  user: "postgres"

  # -- Database password.
  password: "SUPERSTRONGPW"

# -- Define PriorityClass name for pod.
# Ref: https://kubernetes.io/docs/concepts/scheduling-eviction/pod-priority-preemption/#priorityclass
priorityClassName: ""

#  Configure extra options for containers probes.
readinessProbe:
  # -- Enables kubernetes ReadinessProbe.
  enabled: true
  # -- Delay after container start until ReadinessProbe is executed.
  initialDelaySeconds: 5
  # -- Number of failed executions until container is terminated.
  failureThreshold: 6
  # -- Time between probe executions.
  periodSeconds: 10
  # -- Number of successful executions after failed ones until container is marked healthy.
  successThreshold: 1
  # -- Timeout for command return.
  timeoutSeconds: 5

# -- Set the amount of replicas of deployment.
replicaCount: 1

# Configure resource requests and limits.
#
# http://kubernetes.io/docs/user-guide/compute-resources/
#
resources:
  limits:
    # -- The max amount of CPUs to consume.
    cpu: 1
    # -- The max amount of RAM to consume.
    memory: "1Gi"
  requests:
    # -- The amount of CPUs which has to be available on the scheduled node.
    cpu: "250m"
    # -- The amount of RAM which has to be available on the scheduled node.
    memory: "64Mi"

# -- Configure name of Scheduler.
schedulerName: ""

# Define and create Kubernetes Service.
#
# Ref.: https://kubernetes.io/docs/concepts/services-networking/service
service:
  # -- Additional custom annotations.
  annotations: {}

  # -- Define a cluster if needed.
  clusterIP: ""

  # -- Enable kubernetes service creation.
  enabled: true

  # -- The externalTrafficPolicy.
  externalTrafficPolicy: ""

  # -- The loadBalancerSourceRanges.
  loadBalancerSourceRanges: ""

  # "ClusterIP" => Exposes the Service on a cluster-internal IP. Choosing this value makes the Service only reachable
  #                from within the cluster. This is the default that is used if you don't explicitly specify a type for
  #                a Service.
  # "NodePort" => Exposes the Service on each Node's IP at a static port (the NodePort). To make the node port
  #               available, Kubernetes sets up a cluster IP address, the same as if you had requested a Service of
  #               type: ClusterIP.
  # "LoadBalancer" => Exposes the Service externally using a cloud provider's load balancer.
  #
  # Ref.: https://kubernetes.io/docs/concepts/services-networking/service/#publishing-services-service-types

  # -- Choose the kind of Service, one of "ClusterIP", "NodePort" or "LoadBalancer".
  type: "ClusterIP"

  # Define the ports of Service.
  # You can set the port value to an arbitrary value, it will map the container port by name.
  #
  ports:
    postgresql:
      # -- Accessible port.
      port: 5432
      # -- Internal port.
      containerPort: 5432
      # -- Service protocol.
      protocol: "TCP"

  # -- Session affinity type of service.
  sessionAffinity: ""

  # -- Session affinity configuration.
  sessionAffinityConfig: {}

# Service account to use.
# Ref.: https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/
serviceAccount:
  # -- Additional custom annotations for the ServiceAccount.
  annotations: {}

  # -- Allows auto mount of ServiceAccountToken on the serviceAccount created. Can be set to false if pods using this
  # serviceAccount do not need to use K8s API.
  automountServiceAccountToken: false

  # -- Enable creation of ServiceAccount for pod.
  create: true

  # -- Additional custom labels for the ServiceAccount.
  labels: {}

#  Configure extra options for containers probes.
startupProbe:
  # -- Enables kubernetes ReadinessProbe.
  enabled: true
  # -- Delay after container start until ReadinessProbe is executed.
  initialDelaySeconds: 15
  # -- Number of failed executions until container is terminated.
  failureThreshold: 15
  # -- Time between probe executions.
  periodSeconds: 10
  # -- Number of successful executions after failed ones until container is marked healthy.
  successThreshold: 1
  # -- Timeout for command return.
  timeoutSeconds: 1

# -- In seconds, time the given to the pod needs to terminate gracefully.
# Ref: https://kubernetes.io/docs/concepts/workloads/pods/pod/#termination-of-pods
terminationGracePeriodSeconds: 120

# -- Tolerations for pod assignment.
# Ref: https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/
tolerations: []

# -- Topology spread constraints rely on node labels to identify the topology domain(s) that each Node is in.
# Ref: https://kubernetes.io/docs/concepts/workloads/pods/pod-topology-spread-constraints/
#
# topologySpreadConstraints:
#   - maxSkew: 1
#     topologyKey: failure-domain.beta.kubernetes.io/zone
#     whenUnsatisfiable: DoNotSchedule
topologySpreadConstraints: []

# Set up update strategy.
#
# Ref: https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#strategy
#
# Example:
# updateStrategy:
#  type: RollingUpdate
#  rollingUpdate:
#    maxSurge: 25%
#    maxUnavailable: 25%
updateStrategy:
  # -- Set to Recreate if you use persistent volume that cannot be mounted by more than one pods to make sure the pods
  # is destroyed first.
  type: "RollingUpdate"

...
