# =============================================================================
# ox-workspace — OX App Suite deployer
# =============================================================================
# Deploys the appsuite-public-sector Helm chart for a single tenant.
#
# Unlike the generic app-workspace, this module uses templatefile() to render
# a sensitive YAML values file because OX credentials live in deeply nested
# propertiesFiles["/path"].key structures that cannot be expressed as
# individual Helm --set values (the Helm provider rejects them as invalid keys).
#
# Values hierarchy (merged in order, later overrides earlier):
#   1. ${path.module}/../../../services/ox-appsuite/values/_base.yaml — app defaults
#   2. templatefile() sensitive values — credentials from OpenBao
#   3. var.extra_values_json — per-tenant AppProfile.spec.extraValues overrides
#
# OpenBao secret layout (KV v2 mount "secret"):
#   gentian-os/tenants/{tenant_name}/apps/ox-appsuite/oidc
#     client-secret
#   gentian-os/tenants/{tenant_name}/apps/ox-appsuite/database
#     host, port, name, user, password
#   gentian-os/tenants/{tenant_name}/apps/ox-appsuite/s3
#     endpoint, bucket, access-key, secret-key, region
#   gentian-os/tenants/{tenant_name}/apps/ox-appsuite/cache
#     host, port, password
#   gentian-os/tenants/{tenant_name}/apps/ox-appsuite/ldap
#     host, port, base-dn, bind-dn, bind-password
#   gentian-os/tenants/{tenant_name}/apps/ox-appsuite/internal/{name}
#     value
# =============================================================================

terraform {
  required_providers {
    vault = {
      source  = "hashicorp/vault"
      version = "~> 4.0"
    }
    helm = {
      source  = "hashicorp/helm"
      version = "~> 2.0"
    }
  }

  backend "s3" {
    bucket = "tofu-state"
    key    = "placeholder"

    endpoint         = "http://minio-dev.gentian-infra-dev.svc.cluster.local:9000"
    region           = "us-east-1"
    force_path_style = true

    skip_credentials_validation = true
    skip_metadata_api_check     = true
    skip_region_validation      = true
  }
}

# ── Providers ─────────────────────────────────────────────────────────────────

provider "vault" {
  address = "http://openbao.openbao.svc.cluster.local:8200"

  auth_login {
    path = "auth/kubernetes/login"
    parameters = {
      role = "tofu-runner"
      jwt  = file("/var/run/secrets/kubernetes.io/serviceaccount/token")
    }
  }
}

provider "helm" {
  kubernetes {
    host                   = "https://kubernetes.default.svc"
    token                  = file("/var/run/secrets/kubernetes.io/serviceaccount/token")
    cluster_ca_certificate = file("/var/run/secrets/kubernetes.io/serviceaccount/ca.crt")
  }

  dynamic "registry" {
    for_each = var.registry_username != "" ? [1] : []
    content {
      url      = "oci://${split("/", trimprefix(var.chart_repository, "oci://"))[0]}"
      username = var.registry_username
      password = var.registry_password
    }
  }
}

# ── Locals ────────────────────────────────────────────────────────────────────

locals {
  secret_base = "gentian-os/tenants/${var.tenant_name}/apps/ox-appsuite"
}

# ── OpenBao data sources ───────────────────────────────────────────────────────

data "vault_kv_secret_v2" "oidc" {
  mount = "secret"
  name  = "${local.secret_base}/oidc"
}

data "vault_kv_secret_v2" "database" {
  mount = "secret"
  name  = "${local.secret_base}/database"
}

data "vault_kv_secret_v2" "s3" {
  mount = "secret"
  name  = "${local.secret_base}/s3"
}

data "vault_kv_secret_v2" "cache" {
  mount = "secret"
  name  = "${local.secret_base}/cache"
}

data "vault_kv_secret_v2" "ldap" {
  mount = "secret"
  name  = "${local.secret_base}/ldap"
}

# App-internal secrets (generated by the orchestrator and stored per-name).
data "vault_kv_secret_v2" "internal_admin_password" {
  mount = "secret"
  name  = "${local.secret_base}/internal/admin_password"
}

data "vault_kv_secret_v2" "internal_hz_group_password" {
  mount = "secret"
  name  = "${local.secret_base}/internal/hz_group_password"
}

data "vault_kv_secret_v2" "internal_basic_auth_password" {
  mount = "secret"
  name  = "${local.secret_base}/internal/basic_auth_password"
}

data "vault_kv_secret_v2" "internal_jolokia_password" {
  mount = "secret"
  name  = "${local.secret_base}/internal/jolokia_password"
}

data "vault_kv_secret_v2" "internal_cookie_hash_salt" {
  mount = "secret"
  name  = "${local.secret_base}/internal/cookie_hash_salt"
}

data "vault_kv_secret_v2" "internal_share_crypt_key" {
  mount = "secret"
  name  = "${local.secret_base}/internal/share_crypt_key"
}

data "vault_kv_secret_v2" "internal_sessiond_encryption_key" {
  mount = "secret"
  name  = "${local.secret_base}/internal/sessiond_encryption_key"
}

# ── Sensitive values template ─────────────────────────────────────────────────
# Renders a YAML values file with all sensitive credentials from OpenBao.
# The template uses the same structure as the opendesk helmfile's
# values-sensitive.yaml.tftpl so the chart receives credentials in the exact
# format it expects (including propertiesFiles["/path"].key hierarchies).

locals {
  sensitive_values_yaml = sensitive(templatefile(
    "${path.module}/../../../services/ox-appsuite/values/sensitive.yaml.tftpl",
    {
      # OIDC
      oidc_client_secret = data.vault_kv_secret_v2.oidc.data["client-secret"]
      # MariaDB — root/admin password (OX connects as root and manages its schema)
      mariadb_root_password = data.vault_kv_secret_v2.database.data["password"]
      # S3 / MinIO
      minio_ox_password = data.vault_kv_secret_v2.s3.data["secret-key"]
      # Redis session store
      redis_auth_password = data.vault_kv_secret_v2.cache.data["password"]
      # LDAP bind password
      ldap_ox_password = data.vault_kv_secret_v2.ldap.data["bind-password"]
      # App-internal secrets
      admin_password          = data.vault_kv_secret_v2.internal_admin_password.data["value"]
      hz_group_password       = data.vault_kv_secret_v2.internal_hz_group_password.data["value"]
      basic_auth_password     = data.vault_kv_secret_v2.internal_basic_auth_password.data["value"]
      jolokia_password        = data.vault_kv_secret_v2.internal_jolokia_password.data["value"]
      cookie_hash_salt        = data.vault_kv_secret_v2.internal_cookie_hash_salt.data["value"]
      share_crypt_key         = data.vault_kv_secret_v2.internal_share_crypt_key.data["value"]
      sessiond_encryption_key = data.vault_kv_secret_v2.internal_sessiond_encryption_key.data["value"]
    }
  ))
}

# ── Helm release ───────────────────────────────────────────────────────────────

resource "helm_release" "ox_appsuite" {
  name       = "open-xchange"
  repository = var.chart_repository
  chart      = var.chart_name
  version    = var.chart_version
  namespace  = var.namespace

  create_namespace = false
  wait             = true
  timeout          = 1200
  # replace=true maps to helm install --replace, which handles the case where
  # the release already exists in a deployed state when Terraform has no prior
  # state (e.g. first run after backend migration). With persistent state,
  # Terraform uses helm upgrade on subsequent runs and this flag has no effect.
  replace = true

  # Values are merged in order: base config → sensitive credentials → per-tenant overrides.
  # This mirrors the opendesk helmfile layer structure:
  #   values/_base.yaml (non-sensitive defaults)
  #   values/sensitive.yaml.tftpl (credentials from OpenBao)
  #   AppProfile.spec.extraValues (per-tenant overrides via extra_values_json)
  values = compact([
    file("${path.module}/../../../services/ox-appsuite/values/_base.yaml"),
    local.sensitive_values_yaml,
    var.extra_values_json != "" ? var.extra_values_json : "",
  ])
}

# ── opendesk-open-xchange-bootstrap ──────────────────────────────────────────
# One-shot Job that initialises the OX configdb schema: creates the context,
# registers the S3 filestore, and sets the default context admin.
# Must run after the main OX App Suite chart is fully ready.
# Subsequent Terraform runs are no-ops if chart values are unchanged.

resource "helm_release" "ox_bootstrap" {
  depends_on = [helm_release.ox_appsuite]

  name       = "opendesk-open-xchange-bootstrap"
  repository = "oci://registry.opencode.de/bmi/opendesk/components/platform-development/charts/opendesk-open-xchange-bootstrap"
  chart      = "opendesk-open-xchange-bootstrap"
  version    = "4.0.2"
  namespace  = var.namespace

  create_namespace = false
  wait             = true
  timeout          = 600

  # Reduced filestore quota for dev (10 GB instead of the default 100 GB).
  set {
    name  = "filestore.size"
    value = "10000"
  }
}

# ── ox-connector ──────────────────────────────────────────────────────────────
# Listens on the Nubus UDM provisioning API and syncs users/groups into OX.
# Requires:
#   - The provisioning API secret "ox-connector-provisioning-api" (created by
#     ExternalSecret in the tenant namespace via the ESO ClusterSecretStore).
#   - Egress from the tenant NetworkPolicy to the gentian-dev namespace (where
#     the Nubus provisioning API lives).

resource "helm_release" "ox_connector" {
  depends_on = [helm_release.ox_bootstrap]

  name       = "ox-connector"
  repository = "oci://registry.opencode.de/bmi/opendesk/components/supplier/univention/charts-mirror"
  chart      = "ox-connector"
  version    = "0.34.0"
  namespace  = var.namespace

  create_namespace = false
  wait             = false # connector is a long-lived service, not a job
  timeout          = 300

  set {
    name  = "openXchange.domainName"
    value = "desk.gentian.org"
  }

  set {
    name  = "openXchange.auth.username"
    value = "admin"
  }

  set {
    name  = "openXchange.oxDefaultContext"
    value = "1"
  }

  set {
    name  = "openXchange.oxSoapServer"
    value = "http://open-xchange-core-mw-admin.${var.namespace}.svc.cluster.local"
  }

  set {
    name  = "openXchange.oxLocalTimezone"
    value = "Europe/Berlin"
  }

  set {
    name  = "openXchange.oxLanguage"
    value = "de_DE"
  }

  set {
    name  = "openXchange.oxSmtpServer"
    value = "smtp://postfix-${var.tenant_name}-mail.${var.namespace}.svc.cluster.local:587"
  }

  set {
    name  = "openXchange.oxImapServer"
    value = "imap://dovecot-${var.tenant_name}-docker-mailserver.${var.namespace}.svc.cluster.local:143"
  }

  set {
    name  = "provisioningApi.connection.baseUrl"
    value = "http://nubus-dev-provisioning-api.gentian-dev.svc.cluster.local"
  }

  set {
    name  = "provisioningApi.auth.username"
    value = "ox-connector"
  }

  set {
    name  = "provisioningApi.auth.existingSecret.name"
    value = "ox-connector-provisioning-api"
  }

  set_sensitive {
    name  = "openXchange.auth.password"
    value = data.vault_kv_secret_v2.internal_admin_password.data["value"]
  }
}
