/*
Copyright The Gentian OS Authors.

This Source Code Form is subject to the terms of the Mozilla Public
License, v. 2.0. If a copy of the MPL was not distributed with this
file, You can obtain one at https://mozilla.org/MPL/2.0/.

SPDX-License-Identifier: MPL-2.0
*/

// Code generated by scripts/gen/gen-definitions.py. DO NOT EDIT.

package crdcheck

// The operator reads the definitions it was built with, each by its name, to
// see whether the cluster serves every field of them. Read, one object at a
// time, of these and of nothing else: no list and no watch, which a rule
// naming resources cannot restrict, and no other CustomResourceDefinition.
//
// The names are every CRD in charts/gentian-os/crds and, for every XRD in
// crossplane/xrds, the composite and the claim CRD Crossplane generates from
// it. Run `make manifests` after adding a definition.
//
// The marker is a free-floating block: controller-gen ignores a block that is
// part of a declaration's doc comment.
//
// +kubebuilder:rbac:groups=apiextensions.k8s.io,resources=customresourcedefinitions,resourceNames=appgrants.gentianos.io;apppackages.gentianos.io;apps.gentianos.io;backuppolicies.gentianos.io;brandings.gentianos.io;clusters.gentianos.io;componentprofiles.gentianos.io;components.gentianos.io;credentialrequirements.gentianos.io;customizations.gentianos.io;integrationbindings.gentianos.io;oidcpackcatalogs.gentianos.io;platformsecuritypolicies.gentianos.io;repositories.gentianos.io;resourceplans.gentianos.io;suze.gentianos.io;tenantbackuppolicies.gentianos.io;tenantdomains.gentianos.io;tenantexports.gentianos.io;tenantexportschedules.gentianos.io;tenantrestores.gentianos.io;tenants.gentianos.io;xapps.gentianos.io;xclusters.gentianos.io;xrepositories.gentianos.io;xsuze.gentianos.io;xtenants.gentianos.io,verbs=get
